import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { autosRiverSourceNotes, autosRiverStories } from "../src/components/autos-river-data";
import { ewRiverSourceNotes, ewRiverStories } from "../src/components/ew-river-data";
import { fluxRiverSourceNotes, fluxRiverStories } from "../src/components/flux-river-data";
import {
  lifestyleRiverSourceNotes,
  lifestyleRiverStories,
} from "../src/components/lifestyle-river-data";
import type { LifestyleRiverStory } from "../src/components/lifestyle-river-types";

const STORIES_PER_BRAND = 3;
const GALLERY_IMAGES_PER_BRAND = 7;
const MINIMUM_GALLERY_IMAGES = 5;
const outputPath = resolve("src/stories/generated/hearst-plus-fixtures.ts");

const sourceData = {
  lifestyle: { stories: lifestyleRiverStories, sourceNotes: lifestyleRiverSourceNotes },
  autos: { stories: autosRiverStories, sourceNotes: autosRiverSourceNotes },
  flux: { stories: fluxRiverStories, sourceNotes: fluxRiverSourceNotes },
  ew: { stories: ewRiverStories, sourceNotes: ewRiverSourceNotes },
} as const;

function isGallery(story: LifestyleRiverStory) {
  return /photos|gallery/i.test(`${story.sourceUrl ?? ""} ${story.tags.join(" ")}`);
}

function chooseRepresentativeStories(stories: LifestyleRiverStory[]) {
  const storiesByBrand = new Map<string, LifestyleRiverStory[]>();

  for (const story of stories) {
    const brandStories = storiesByBrand.get(story.brandSlug) ?? [];
    brandStories.push(story);
    storiesByBrand.set(story.brandSlug, brandStories);
  }

  return [...storiesByBrand.values()].flatMap((brandStories) => {
    const chosen: LifestyleRiverStory[] = [];
    const add = (story: LifestyleRiverStory | undefined) => {
      if (story && !chosen.some((candidate) => candidate.id === story.id)) chosen.push(story);
    };

    add(brandStories.find((story) => story.mediaKind === "video" || Boolean(story.videoUrl)));
    add(brandStories.find(isGallery));
    add(brandStories.find((story) => !story.videoUrl && !isGallery(story)));

    for (const story of brandStories) {
      add(story);
      if (chosen.length >= STORIES_PER_BRAND) break;
    }

    return chosen.slice(0, STORIES_PER_BRAND);
  });
}

type StorybookGalleryImage = {
  src: string;
  alt: string;
  credit?: string;
};

function toGalleryImage(story: LifestyleRiverStory): StorybookGalleryImage {
  return {
    src: story.image,
    alt: story.title,
    ...(story.imageCredit ? { credit: story.imageCredit } : {}),
  };
}

function chooseGalleryImages(stories: LifestyleRiverStory[]) {
  const storiesByBrand = new Map<string, LifestyleRiverStory[]>();

  for (const story of stories) {
    const brandStories = storiesByBrand.get(story.brandSlug) ?? [];
    brandStories.push(story);
    storiesByBrand.set(story.brandSlug, brandStories);
  }

  return Object.fromEntries([...storiesByBrand].map(([brandSlug, brandStories]) => {
    const images: StorybookGalleryImage[] = [];
    const add = (story: LifestyleRiverStory) => {
      if (!story.image || images.some((image) => image.src === story.image)) return;
      images.push(toGalleryImage(story));
    };

    // Prefer gallery-labelled stories, then use the rest of the publication's
    // checked-in feed. This keeps the Storybook mosaic deterministic while
    // avoiding the compact three-story component fixture as an image source.
    brandStories.filter(isGallery).forEach(add);
    brandStories.forEach(add);

    // A publication may temporarily have fewer than five distinct imported
    // images. Fill that rare gap from its destination so the rich-gallery
    // fixture still exercises the production five-image upgrade threshold.
    if (images.length < MINIMUM_GALLERY_IMAGES) {
      stories.forEach(add);
    }

    return [brandSlug, images.slice(0, GALLERY_IMAGES_PER_BRAND)];
  }));
}

const compactData = Object.fromEntries(
  Object.entries(sourceData).map(([destination, data]) => [
    destination,
    {
      stories: chooseRepresentativeStories(data.stories),
      sourceNotes: data.sourceNotes,
    },
  ])
);

const galleryImagesByBrand = Object.assign(
  {},
  ...Object.values(sourceData).map((data) => chooseGalleryImages(data.stories))
) satisfies Record<string, StorybookGalleryImage[]>;

const header = `// Generated by scripts/generate-storybook-fixtures.ts.
// A compact, representative subset of the checked-in Hearst feeds for deterministic Storybook demos.
// Run \`npm run storybook:fixtures\` after refreshing production feed data.

import type { LifestyleRiverStory } from "@/components/lifestyle-river-types";
import type { HearstDestinationSourceNote } from "@/lib/hearst-destination-data-types";

export type StorybookFixtureDestination = {
  stories: LifestyleRiverStory[];
  sourceNotes: readonly HearstDestinationSourceNote[];
};

export type StorybookGalleryImage = {
  src: string;
  alt: string;
  credit?: string;
};

`;

const output = `${header}export const storybookFixtureData = ${JSON.stringify(compactData, null, 2)} satisfies Record<"lifestyle" | "autos" | "flux" | "ew", StorybookFixtureDestination>;

export const storybookGalleryImagesByBrand: Record<string, StorybookGalleryImage[]> = ${JSON.stringify(galleryImagesByBrand, null, 2)};
`;

async function main() {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");

  const storyCount = Object.values(compactData).reduce(
    (total, destination) => total + destination.stories.length,
    0
  );
  console.log(`Generated ${storyCount} representative Storybook stories at ${outputPath}.`);
}

void main();
