/**
 * Sync from Pencil → App
 *
 * Reads the Pencil .pen file variables (via exported JSON) and generates:
 *   1. src/lib/brands.ts   — TypeScript brand data
 *   2. src/lib/tokens.css   — CSS custom properties per brand
 *
 * Usage: npx tsx scripts/sync-from-pencil.ts
 */

import * as fs from "fs";
import * as path from "path";

const PENCIL_VARS_PATH = path.resolve(__dirname, "../src/lib/pencil-variables.json");

interface ThemedValue {
  theme: { brand: string };
  value: string;
}

interface PencilVariable {
  type: string;
  value: string | ThemedValue[];
}

interface BrandData {
  name: string;
  slug: string;
  colors: Record<string, string>;
  fontDefault: string;
  fontSecondary: string;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/'/g, "")
    .replace(/&/g, "and")
    .replace(/\s+/g, "-");
}

function resolveThemedValues(entries: ThemedValue[]): Map<string, string> {
  const result = new Map<string, string>();
  for (const entry of entries) {
    result.set(entry.theme.brand, entry.value);
  }
  return result;
}

function main() {
  if (!fs.existsSync(PENCIL_VARS_PATH)) {
    console.error(`Pencil variables file not found at ${PENCIL_VARS_PATH}`);
    console.error("Export variables from Pencil first.");
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(PENCIL_VARS_PATH, "utf-8"));

  const brandNames: string[] = [
    "White Label", "Autoweek", "Best Products", "Bicycling", "Biography",
    "Car and Driver", "Cosmopolitan", "Country Living", "Delish", "ELLE",
    "ELLE Decor", "Esquire", "Good Housekeeping", "Harper's BAZAAR",
    "House Beautiful", "Men's Health", "Oprah Daily", "Popular Mechanics",
    "Prevention", "Redbook", "Road & Track", "Runner's World", "Seventeen",
    "The Pioneer Woman", "Town & Country", "Veranda", "Woman's Day",
    "Women's Health",
  ];

  const colorKeys = ["brand-1", "brand-2", "brand-3", "brand-4", "brand-5", "brand-6"];
  const colorMaps: Record<string, Map<string, string>> = {};
  for (const key of colorKeys) {
    const variable = raw[key] as PencilVariable | undefined;
    if (variable && Array.isArray(variable.value)) {
      colorMaps[key] = resolveThemedValues(variable.value as ThemedValue[]);
    }
  }

  const fontDefaultVar = raw["font-family-default"] as PencilVariable | undefined;
  const fontSecondaryVar = raw["font-family-serif"] as PencilVariable | undefined;
  const fontDefaultMap = fontDefaultVar && Array.isArray(fontDefaultVar.value)
    ? resolveThemedValues(fontDefaultVar.value as ThemedValue[])
    : new Map<string, string>();
  const fontSecondaryMap = fontSecondaryVar && Array.isArray(fontSecondaryVar.value)
    ? resolveThemedValues(fontSecondaryVar.value as ThemedValue[])
    : new Map<string, string>();

  const brands: BrandData[] = brandNames.map((name) => {
    const colors: Record<string, string> = {};
    for (let i = 1; i <= 6; i++) {
      const key = `brand-${i}`;
      const val = colorMaps[key]?.get(name) || "#ffffff";
      colors[String(i)] = val;
    }
    return {
      name,
      slug: slugify(name),
      colors,
      fontDefault: fontDefaultMap.get(name) || "SF Pro",
      fontSecondary: fontSecondaryMap.get(name) || "SF Pro",
    };
  });

  const srcDir = path.resolve(__dirname, "../src/lib");

  const brandsTs = generateBrandsTs(brands);
  fs.writeFileSync(path.join(srcDir, "brands.ts"), brandsTs);
  console.log(`Wrote src/lib/brands.ts (${brands.length} brands)`);

  const tokensCss = generateTokensCss(brands);
  fs.writeFileSync(path.join(srcDir, "tokens.css"), tokensCss);
  console.log(`Wrote src/lib/tokens.css`);

  console.log("\nSync from Pencil complete!");
}

function generateBrandsTs(brands: BrandData[]): string {
  const lines: string[] = [
    "// Auto-generated by scripts/sync-from-pencil.ts — do not edit manually",
    `// Source: hearst-brands.pen | Synced: ${new Date().toISOString()}`,
    "",
    "export interface BrandTheme {",
    "  name: string;",
    "  slug: string;",
    "  colors: Record<string, string>;",
    "  fontDefault: string;",
    "  fontSecondary: string;",
    "}",
    "",
    "export const brands: BrandTheme[] = [",
  ];

  for (const b of brands) {
    const colorsStr = Object.entries(b.colors)
      .sort(([a], [bk]) => parseInt(a) - parseInt(bk))
      .map(([k, v]) => `"${k}": "${v}"`)
      .join(", ");

    lines.push("  {");
    lines.push(`    name: "${b.name}",`);
    lines.push(`    slug: "${b.slug}",`);
    lines.push(`    colors: { ${colorsStr} },`);
    lines.push(`    fontDefault: "${b.fontDefault}",`);
    lines.push(`    fontSecondary: "${b.fontSecondary}",`);
    lines.push("  },");
  }

  lines.push("];");
  return lines.join("\n");
}

function generateTokensCss(brands: BrandData[]): string {
  const lines: string[] = [
    "/* Auto-generated by scripts/sync-from-pencil.ts — do not edit manually */",
    `/* Source: hearst-brands.pen | Synced: ${new Date().toISOString()} */`,
    "",
  ];

  for (const b of brands) {
    const primary = b.colors["1"] || "#000000";
    lines.push(`[data-brand="${b.slug}"] {`);
    lines.push(`  --brand-name: "${b.name}";`);
    lines.push(`  --brand-primary: ${primary};`);
    for (let i = 1; i <= 6; i++) {
      const v = b.colors[String(i)];
      if (v && v.toLowerCase() !== "#ffffff") {
        lines.push(`  --brand-${i}: ${v};`);
      }
    }
    lines.push(`  --font-brand-sans: "${b.fontDefault}", system-ui, sans-serif;`);
    lines.push(`  --font-brand-secondary: "${b.fontSecondary}", Georgia, serif;`);
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

main();
