/**
 * Token Sync Script
 *
 * Single source of truth: Figma Token Studio API
 * Outputs to:
 *   1. src/lib/brands.ts          — Next.js / shadcn theme data
 *   2. src/lib/tokens.css          — CSS custom properties per brand (data-brand attribute)
 *   3. Pencil variables            — via MCP set_variables (when run inside Cursor)
 *
 * Usage:
 *   npx tsx scripts/sync-tokens.ts              # generate code files only
 *   npx tsx scripts/sync-tokens.ts --pencil     # also update Pencil .pen file
 */

const API_URL =
  "https://figma-connector.kubeprod.hearstapps.com/token-studio/tokens";

interface TokenValue {
  $value?: string;
  value?: string;
  type?: string;
  [key: string]: unknown;
}

interface BrandOutput {
  name: string;
  slug: string;
  colors: Record<string, string>;
  fontDefault: string;
  fontSecondary: string;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/'/g, "")
    .replace(/&/g, "and")
    .replace(/\s+/g, "-");
}

function flatten(
  obj: Record<string, unknown>,
  prefix = "",
  result: Record<string, string> = {}
): Record<string, string> {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith("$") || key === "type") continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === "object") {
      const v = val as TokenValue;
      const resolved = v.$value ?? v.value;
      if (typeof resolved === "string") {
        result[path] = resolved;
      }
      flatten(val as Record<string, unknown>, path, result);
    }
  }
  return result;
}

function resolve(
  val: string,
  prims: Record<string, string>,
  depth = 0
): string {
  if (depth > 15 || typeof val !== "string") return val;
  if (val.startsWith("{") && val.endsWith("}")) {
    const ref = val.slice(1, -1);
    if (prims[ref]) return resolve(prims[ref], prims, depth + 1);
    return "";
  }
  return val;
}

async function fetchTokens(): Promise<Record<string, unknown>> {
  const res = await fetch(API_URL);
  if (!res.ok) throw new Error(`Failed to fetch tokens: ${res.status}`);
  return res.json();
}

function parseTokens(data: Record<string, unknown>): {
  brands: BrandOutput[];
  primitives: Record<string, string>;
  sharedTokens: {
    neutral: Record<string, string>;
    spacing: Record<string, number>;
    radius: Record<string, number>;
  };
} {
  const vals = data.values as Record<string, Record<string, unknown>>;

  const prims: Record<string, string> = {};
  for (const key of Object.keys(vals)) {
    if (key.startsWith("Primitives/")) {
      flatten(vals[key], "", prims);
    }
  }

  const brands: BrandOutput[] = [];
  for (const key of Object.keys(vals)) {
    if (!key.startsWith("Alias/")) continue;
    const name = key.replace("Alias/", "");
    const bdata = vals[key] as Record<string, Record<string, unknown>>;

    const brand: BrandOutput = {
      name,
      slug: slugify(name),
      colors: {},
      fontDefault: "system-ui",
      fontSecondary: "Georgia",
    };

    const pal =
      (bdata.palette as Record<string, Record<string, TokenValue>>)?.brand ||
      {};
    for (const [k, v] of Object.entries(pal)) {
      if (v && typeof v === "object") {
        const raw = v.$value ?? v.value ?? "";
        const resolved = resolve(raw, prims);
        if (resolved?.startsWith("#")) {
          brand.colors[k] = resolved;
        }
      }
    }

    const font =
      (bdata.font as Record<string, Record<string, TokenValue>>)?.family || {};
    for (const [k, v] of Object.entries(font)) {
      if (v && typeof v === "object") {
        const raw = v.$value ?? v.value ?? "";
        const resolved = resolve(raw, prims);
        if (resolved && !resolved.startsWith("{")) {
          if (k === "default") brand.fontDefault = resolved;
          if (k === "serif") brand.fontSecondary = resolved;
        }
      }
    }

    brands.push(brand);
  }

  const neutral: Record<string, string> = {};
  for (const [k, v] of Object.entries(prims)) {
    if (k.includes("gray") || k.includes("Grey")) {
      const parts = k.split(".");
      const num = parts[parts.length - 1];
      if (/^\d+$/.test(num)) {
        const resolved = resolve(v, prims);
        if (resolved.startsWith("#")) neutral[num] = resolved;
      }
    }
  }

  return {
    brands,
    primitives: prims,
    sharedTokens: {
      neutral,
      spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, "2xl": 48, "3xl": 64 },
      radius: { sm: 4, md: 8, lg: 12, xl: 16, full: 9999 },
    },
  };
}

function generateBrandsTs(brands: BrandOutput[]): string {
  const lines: string[] = [
    "// Auto-generated by scripts/sync-tokens.ts — do not edit manually",
    `// Last synced: ${new Date().toISOString()}`,
    "",
    "export interface BrandTheme {",
    "  name: string;",
    "  slug: string;",
    "  colors: Record<string, string>;",
    "  fontDefault: string;",
    "  fontSecondary: string;",
    "}",
    "",
    "export const brands: BrandTheme[] = [",
  ];

  for (const b of brands) {
    const colorsStr = Object.entries(b.colors)
      .sort(([a], [b]) => {
        const an = parseInt(a),
          bn = parseInt(b);
        if (!isNaN(an) && !isNaN(bn)) return an - bn;
        return a.localeCompare(b);
      })
      .map(([k, v]) => `"${k}": "${v}"`)
      .join(", ");

    lines.push("  {");
    lines.push(`    name: "${b.name}",`);
    lines.push(`    slug: "${b.slug}",`);
    lines.push(`    colors: { ${colorsStr} },`);
    lines.push(`    fontDefault: "${b.fontDefault}",`);
    lines.push(`    fontSecondary: "${b.fontSecondary}",`);
    lines.push("  },");
  }

  lines.push("];");
  return lines.join("\n");
}

function generateTokensCss(brands: BrandOutput[]): string {
  const lines: string[] = [
    "/* Auto-generated by scripts/sync-tokens.ts — do not edit manually */",
    `/* Last synced: ${new Date().toISOString()} */`,
    "",
  ];

  for (const b of brands) {
    const primary =
      b.colors["1"] || Object.values(b.colors)[0] || "#000000";
    const meaningful = Object.entries(b.colors).filter(
      ([, v]) => v.toLowerCase() !== "#ffffff"
    );

    lines.push(`[data-brand="${b.slug}"] {`);
    lines.push(`  --brand-name: "${b.name}";`);
    lines.push(`  --brand-primary: ${primary};`);
    for (const [k, v] of meaningful) {
      lines.push(`  --brand-${k}: ${v};`);
    }
    lines.push(`  --font-brand-sans: "${b.fontDefault}", system-ui, sans-serif;`);
    lines.push(`  --font-brand-serif: "${b.fontSecondary}", Georgia, serif;`);
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function generatePencilVariables(brands: BrandOutput[]): Record<string, unknown> {
  const variables: Record<string, unknown> = {};

  const brandColorKeys = ["1", "2", "3", "4", "5", "6"];
  for (const key of brandColorKeys) {
    const themed = brands
      .map((b) => ({
        value: b.colors[key] || "#ffffff",
        theme: { brand: b.name },
      }));
    variables[`brand-${key}`] = { type: "color", value: themed };
  }

  variables["font-family-default"] = {
    type: "string",
    value: brands.map((b) => ({
      value: b.fontDefault || "SF Pro",
      theme: { brand: b.name },
    })),
  };

  variables["font-family-serif"] = {
    type: "string",
    value: brands.map((b) => ({
      value: b.fontSecondary || "Georgia",
      theme: { brand: b.name },
    })),
  };

  return variables;
}

async function main() {
  const fs = await import("fs");
  const path = await import("path");

  console.log("Fetching tokens from API...");
  const data = await fetchTokens();

  console.log("Parsing tokens...");
  const { brands } = parseTokens(data as Record<string, unknown>);
  console.log(`Found ${brands.length} brands`);

  const srcDir = path.resolve(__dirname, "../src/lib");

  const brandsTs = generateBrandsTs(brands);
  fs.writeFileSync(path.join(srcDir, "brands.ts"), brandsTs);
  console.log(`Wrote src/lib/brands.ts (${brands.length} brands)`);

  const tokensCss = generateTokensCss(brands);
  fs.writeFileSync(path.join(srcDir, "tokens.css"), tokensCss);
  console.log(`Wrote src/lib/tokens.css`);

  const pencilVars = generatePencilVariables(brands);
  const pencilPath = path.join(srcDir, "pencil-variables.json");
  fs.writeFileSync(pencilPath, JSON.stringify(pencilVars, null, 2));
  console.log(`Wrote src/lib/pencil-variables.json (for Pencil MCP sync)`);

  console.log("\nSync complete!");
  console.log("To update Pencil, use the pencil-variables.json with set_variables MCP tool.");
}

main().catch(console.error);
