import type { ComponentMetadata } from "@/lib/component-metadata";

const metadata: ComponentMetadata = {
  name: "Theme Provider",
  description:
    "Production runtime boundary that resolves the active Hearst destination or publication theme, exposes brand and color-mode controls, applies generated CSS variables, and loads supported preview fonts.",
  level: "molecule",
  path: "theme-provider.tsx",
  exports: [
    "ThemeContext",
    "ThemeProvider",
    "ThemeColorMode",
    "ThemeContextType",
    "useTheme",
  ],
  whenToUse: [
    "A routed Hearst experience needs production brand tokens and theme context",
    "A component tree reads the active publication or destination brand through useTheme",
    "A product surface supports the shared light and dark color-mode contract",
  ],
  whenNotToUse: [
    "A component only needs a local decorative color — consume semantic tokens instead of creating a nested provider",
    "Storybook needs to change its selected brand toolbar value — the global ThemeDecorator adapts that control to this contract",
    "An isolated reader surface owns a separate paper-theme preference — keep that preference local to the reader",
  ],
  tokens: {
    colors: [
      { variable: "--background", via: "css-var", usage: "active surface background" },
      { variable: "--foreground", via: "css-var", usage: "active default content color" },
      { variable: "--primary", via: "css-var", usage: "active brand action color" },
      { variable: "--brand-*", via: "css-var", usage: "publication palette values" },
      { variable: "--palette-*", via: "css-var", usage: "semantic production colors" },
      { variable: "--component-*", via: "css-var", usage: "component-level production decisions" },
    ],
    typography: [
      { variable: "--font-brand", via: "css-var", usage: "primary brand typeface stack" },
      { variable: "--font-brand-secondary", via: "css-var", usage: "secondary editorial typeface stack" },
      { variable: "--font-headline", via: "css-var", usage: "headline typeface stack" },
      { variable: "--font-headline-weight", via: "css-var", usage: "headline weight" },
    ],
    spacing: [],
    borders: [],
    other: [],
  },
  dependencies: [],
  usedBy: [
    "accordion-page",
    "article-page",
    "badge-page",
    "brand-switcher",
    "button-page",
    "card-page",
    "carousel-page",
    "chip-page",
    "color-page",
    "divider-page",
    "form-label-page",
    "utility-bar",
    "home-page",
    "homepage-layouts",
    "hot-rod-events-page",
    "image-page",
    "input-page",
    "layout-page",
    "link-page",
    "media-page",
    "nav-bar",
    "pagination-page",
    "token-dashboard",
    "tokens-page",
    "typography-page",
  ],
  brandAware: true,
  responsive: false,
  variants: [
    "publication brand",
    "destination brand",
    "light color mode",
    "dark color mode",
    "non-persistent preview",
  ],
  caveats: [
    "The default brand is an initial value. Production routes mount the provider at their route boundary rather than changing defaultBrandSlug on an existing instance.",
    "Color-mode persistence is namespaced by the route provider's default brand slug. Storybook and deterministic tests disable persistence.",
    "Unsupported hosted font family names retain the generated runtime fallback stack; the provider only requests families explicitly mapped to Google Fonts.",
    "Storybook's global decorator is an adapter for toolbar-selected brands. Direct Theme Runtime stories mount this exact provider to verify production brand switching, CSS variables, dark mode, and persistence behavior.",
  ],
  storybook: {
    kind: "direct",
    stories: [
      "src/stories/ArticleCard.stories.tsx",
      "src/stories/FRE.stories.tsx",
      "src/stories/HearstPlusAmbientReader.stories.tsx",
      "src/stories/HearstPlusApp.stories.tsx",
      "src/stories/HearstPlusDiscoverySidebar.stories.tsx",
      "src/stories/HearstPlusReaderOverlays.stories.tsx",
      "src/stories/HomePage.stories.tsx",
      "src/stories/LifestyleDestinationApp.stories.tsx",
      "src/stories/ThemeRuntime.stories.tsx",
      "src/stories/Typography.stories.tsx",
    ],
    rationale:
      "ThemeRuntime directly mounts the exact production ThemeProvider and verifies its context, generated variables, brand switching, Hearst Flux dark default, mode toggling, root color-scheme synchronization, and disabled-persistence boundary. The other listed stories are source-graph consumers of the provider; the global decorator separately implements the same complete context shape for their previews.",
  },
};

export default metadata;
