import type { Metadata } from "next";
import Link from "next/link";
import { BrandPortfolioGrid, DemoNav, DestinationConvergence, JourneyMatrix, ProductFooter, ProductHeader, StoryCard, journeys, prototypeStats, streams, valueProps } from "@/components/product-story-shell";

export const metadata: Metadata = { title: "The Hearst Magazines Product Story", description: "The vision, value and reader experience behind a personalized Hearst Magazines destination." };

export default function ProductStoryPage() {
  return <div className="min-h-screen bg-[#F8FAFC] text-[#102A43]">
    <ProductHeader current="story" />
    <main>
      <section className="overflow-hidden border-b border-slate-200 bg-white">
        <div className="mx-auto grid max-w-[1360px] gap-12 px-5 py-20 md:px-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28">
          <div><p className="mb-6 text-xs font-black uppercase tracking-[0.22em] text-[#2D75B9]">The product story</p><h1 className="max-w-3xl font-serif text-6xl leading-[.92] tracking-[-0.045em] md:text-8xl">One destination.<br/><em className="text-[#2D75B9]">Every interest.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-600 md:text-xl">Hearst Magazines turns a portfolio of trusted brands into a personalized daily river, useful enough to become a habit and distinctive enough to feel editorial.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/hearst-all/" className="bg-[#2D75B9] px-5 py-3 text-sm font-bold text-white">Experience the prototype</Link><a href="#vision" className="border border-slate-300 px-5 py-3 text-sm font-bold">Read the story</a></div></div>
          <div className="relative py-8"><div className="absolute left-1/2 top-0 h-full w-2 -translate-x-1/2 bg-[#2D75B9]" />{streams.map((s,i)=><div key={s.name} className={`relative z-10 mb-4 flex ${i%2 ? "justify-end" : "justify-start"}`}><div className="w-[72%] bg-white p-4 shadow-[0_8px_30px_rgba(16,42,67,.1)]" style={{borderLeft:`5px solid ${s.color}`}}><strong>{s.name}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{s.copy}</p></div></div>)}</div>
        </div>
      </section>

      <section id="vision" className="mx-auto max-w-[1360px] px-5 py-20 md:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">The opportunity</p><h2 className="mt-4 font-serif text-5xl leading-none">From a portfolio to a relationship.</h2><p className="mt-6 leading-7 text-slate-600">Readers do not wake up wanting to visit a list of websites. They wake up with needs, curiosities and ambitions. The destination organizes Hearst around those moments.</p></div><DemoNav /></div></section>

      <section className="border-y border-slate-200 bg-white py-20 lg:py-28"><div className="mx-auto max-w-[1360px] px-5 md:px-10"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">How the portfolio unites</p><h2 className="mt-4 font-serif text-5xl leading-none">Four destinations feed one personalized river.</h2><p className="mt-6 leading-7 text-slate-600">The product keeps the portfolio legible for stakeholders and useful for readers. Lifestyle, Autos, Flux and E&amp;W each retain brand meaning, while the unified river can assemble the best next story for the reader&apos;s current intent.</p></div><DestinationConvergence /></div></div></section>

      <section className="border-y border-slate-200 bg-white py-20 lg:py-28"><div className="mx-auto max-w-[1360px] px-5 md:px-10"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">Prototype scope</p><h2 className="mt-4 font-serif text-5xl leading-none">A working model with real brands, real story metadata and real image behavior.</h2><p className="mt-6 leading-7 text-slate-600">The prototype is not a generic mockup. It uses public Hearst RSS metadata, canonical story links and real Hearst CDN images so stakeholders can evaluate the editorial, product and commercial experience with realistic constraints.</p></div><div className="grid gap-px bg-slate-200 sm:grid-cols-3">{prototypeStats.map((stat)=><article key={stat.label} className="bg-[#F8FAFC] p-6"><strong className="font-serif text-5xl leading-none">{stat.value}</strong><p className="mt-3 text-sm font-black uppercase tracking-[.14em] text-[#2D75B9]">{stat.label}</p><p className="mt-3 text-sm leading-6 text-slate-600">{stat.copy}</p></article>)}</div></div></div></section>

      <section className="mx-auto max-w-[1360px] px-5 py-20 md:px-10 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.55fr_1.45fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">Brand representation</p><h2 className="mt-4 font-serif text-5xl leading-none">Every brand stays recognizable inside the larger destination.</h2><p className="mt-6 leading-7 text-slate-600">These brands matter to stakeholders because each one carries its own audience, authority and commercial promise. The prototype uses brand SVG logos on individual brand routes, brand color and type treatments, and visible brand attribution on cards so the portfolio feels united without flattening the identity of each publication.</p><p className="mt-5 leading-7 text-slate-600">The benefit of uniting them is simple: readers can start with a need instead of a site name, while each brand gains new discovery from adjacent intent. Home, shopping, wellness, style, autos, culture and fitness can cross-pollinate when the reader&apos;s context makes that useful.</p></div><BrandPortfolioGrid /></div></section>

      <section className="bg-[#102A43] py-20 text-white lg:py-28"><div className="mx-auto max-w-[1360px] px-5 md:px-10"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-sky-300">The daily habit</p><h2 className="mt-4 font-serif text-5xl leading-none md:text-6xl">A journey that gets more useful, not more demanding.</h2></div><div className="mt-12 grid gap-px bg-white/20 md:grid-cols-3">{journeys.map((j,i)=><article key={j.title} className="bg-[#102A43] p-7"><span className="text-sm text-sky-300">0{i+1}</span><h3 className="mt-16 text-xl font-bold">{j.title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{j.copy}</p></article>)}</div></div></section>

      <section className="mx-auto max-w-[1360px] px-5 py-20 md:px-10 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">User journeys</p><h2 className="mt-4 font-serif text-5xl leading-none">The habit loop is visible, not hidden in a model.</h2><p className="mt-6 leading-7 text-slate-600">The destination should be explainable to product, editorial and business teams. Each journey turns reader action into a clearer next visit, while preserving controls such as save, follow, hide and clear.</p></div><JourneyMatrix /></div></section>

      <section className="mx-auto max-w-[1360px] px-5 py-20 md:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-2 lg:items-start"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">Personal by design</p><h2 className="mt-4 max-w-xl font-serif text-5xl leading-none">The reader teaches the river through ordinary actions.</h2><p className="mt-6 max-w-xl leading-7 text-slate-600">The system starts with a balanced editorial mix, then learns from explicit signals, follows, saves and hides, plus implicit behavior such as opens, depth and recency. Every result remains explainable and controllable.</p><div className="mt-8 space-y-4">{["Cold start uses editorial priorities and broad interests","Every score balances affinity, freshness, quality and variety","Brand and topic diversity prevent a narrow filter bubble","Controls reveal why something appears and let readers tune it"].map((x,i)=><div key={x} className="grid grid-cols-[2.5rem_minmax(0,1fr)] border-b border-slate-200 pb-4 text-sm font-semibold"><span className="font-mono text-xs text-[#2D75B9]">0{i+1}</span>{x}</div>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><StoryCard/><StoryCard ad/></div></div></section>

      <section className="border-y border-slate-200 bg-white py-20 lg:py-28"><div className="mx-auto max-w-[1360px] px-5 md:px-10"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">Value exchange</p><h2 className="mt-4 font-serif text-5xl leading-none">One experience. Four kinds of value.</h2></div><div className="grid gap-px bg-slate-200 sm:grid-cols-2">{valueProps.map((v,i)=><article key={v.title} className="bg-white p-6"><span className="font-mono text-xs text-[#2D75B9]">0{i+1}</span><h3 className="mt-8 text-lg font-bold">{v.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{v.copy}</p></article>)}</div></div></div></section>

      <section className="mx-auto max-w-[1360px] px-5 py-20 md:px-10 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#2D75B9]">Destination map</p><h2 className="mt-4 font-serif text-5xl leading-none">Many doors. One coherent system.</h2></div><div className="grid gap-px bg-slate-200 sm:grid-cols-2">{[["Unified river","/hearst-all/"],["Lifestyle","/hearst-edit/"],["Autos","/hearst-plus/"],["Flux","/hearst-flux/"],["E&W","/hearst-ew/"],["Brand destinations","/brands/[brandSlug]/"]].map(([n,r])=><div key={n} className="bg-[#F8FAFC] p-5"><span className="text-sm font-bold">{n}</span><code className="mt-2 block text-xs text-slate-500">{r}</code></div>)}</div></div><div className="mt-16 flex flex-col justify-between gap-6 border-t border-slate-300 pt-8 md:flex-row md:items-center"><div><h3 className="font-serif text-3xl">Ready for the system behind the story?</h3><p className="mt-2 text-slate-600">Explore architecture, ranking, routes, measurement and delivery.</p></div><Link href="/hearst-product-blueprint/" className="font-bold text-[#2D75B9]">Open the product blueprint</Link></div></section>
    </main><ProductFooter />
  </div>;
}
