import type { ComponentMetadata } from "@/lib/component-metadata";

const metadata: ComponentMetadata = {
  name: "Button",
  description:
    "Production action control with brand-specific component-token states, compact and touch-safe sizes, loading behavior, and Base UI semantics.",
  level: "atom",
  path: "ui/button.tsx",
  exports: ["Button", "ButtonProps", "buttonVariants"],

  whenToUse: [
    "A user action changes state, submits data, opens a surface, or confirms a decision",
    "Form submissions",
    "Dialog triggers and confirmations",
    "Reader actions and calls to action",
  ],
  whenNotToUse: [
    "Navigation to another URL — use Link; the link visual variant remains a button action",
    "Toggling a boolean state — use Switch or Toggle",
    "Selecting from options — use Chip or ToggleGroup",
  ],

  tokens: {
    colors: [
      { variable: "--component-button-background-primary-solid-default", via: "css-var", usage: "default background" },
      { variable: "--component-button-background-primary-solid-hover", via: "css-var", usage: "default hover background" },
      { variable: "--component-button-background-primary-solid-active", via: "css-var", usage: "default active background" },
      { variable: "--component-button-border-primary-solid-default", via: "css-var", usage: "default border" },
      { variable: "--component-button-content-primary-solid-default", via: "css-var", usage: "default content" },
      { variable: "--component-button-content-primary-solid-hover", via: "css-var", usage: "default hover content" },
      { variable: "--component-button-content-primary-solid-active", via: "css-var", usage: "default active content" },
      { variable: "--component-button-background-secondary-solid-default", via: "css-var", usage: "secondary background" },
      { variable: "--component-button-background-secondary-solid-hover", via: "css-var", usage: "secondary hover background" },
      { variable: "--component-button-background-secondary-solid-active", via: "css-var", usage: "secondary active background" },
      { variable: "--component-button-content-secondary-solid-default", via: "css-var", usage: "secondary content" },
      { variable: "--component-button-background-neutral-outlined-default", via: "css-var", usage: "outline background" },
      { variable: "--component-button-border-neutral-outlined-default", via: "css-var", usage: "outline border" },
      { variable: "--component-button-content-neutral-outlined-default", via: "css-var", usage: "outline content" },
      { variable: "--component-button-background-neutral-transparent-hover", via: "css-var", usage: "ghost hover background" },
      { variable: "--component-button-content-neutral-transparent-default", via: "css-var", usage: "ghost content" },
      { variable: "--component-button-background-primary-transparent-default", via: "css-var", usage: "link-action background" },
      { variable: "--component-button-border-primary-transparent-default", via: "css-var", usage: "link-action border" },
      { variable: "--component-button-content-primary-transparent-default", via: "css-var", usage: "link-action content" },
      { variable: "--destructive", via: "tailwind", usage: "bg-destructive" },
      { variable: "--ring", via: "tailwind", usage: "ring-ring/50" },
    ],
    typography: [],
    spacing: [],
    borders: [
      { variable: "--component-button-radius-default", via: "css-var", usage: "button radius" },
    ],
    other: [],
  },

  dependencies: ["ui/icons"],
  usedBy: [
    "adaptive-video",
    "article-page",
    "button-page",
    "card-page",
    "site-header",
    "content-reader-comments",
    "content-reader-masthead",
    "discovery-sidebar",
    "featured-story-carousel",
    "feed-states",
    "hearst-games-index",
    "onboarding-modal",
    "reader-masthead-carousel",
    "stakeholder-personalization-console",
    "story-actions",
    "utility-bar",
    "video-cards",
    "home-page",
    "homepage-layouts",
    "hot-rod-events-page",
    "reader-account-ui",
    "carousel",
  ],
  brandAware: true,
  responsive: false,
  variants: ["default", "destructive", "outline", "secondary", "ghost", "link"],
  slots: ["leading icon", "label", "trailing icon"],
  caveats: [
    "The default, secondary, outline, and ghost variants consume each publication's registered component/button state tokens rather than approximating hover and active colors from generic semantic tokens.",
    "Sizes xs through lg and icon-xs through icon-lg are dense-layout options below 44px. Use touch or icon-touch, or an explicit min-h-11/size-11 override, for phone actions and other touch-critical controls.",
    "The link variant is a low-emphasis button action; navigation still requires the Link component so URL, history, and browser semantics remain correct.",
    "loading disables activation, exposes aria-busy, retains a visible label, and uses the official Phosphor SpinnerGap icon with reduced-motion fallback.",
    "Icon-only buttons require an explicit accessible name through aria-label or visually hidden text.",
  ],
  storybook: {
    kind: "direct",
    stories: [
      "src/stories/Button.stories.tsx",
      "src/stories/Card.stories.tsx",
      "src/stories/HearstPlusOnboarding.stories.tsx",
      "src/stories/HearstPlusReaderAccount.stories.tsx",
      "src/stories/HearstPlusStakeholderPersonalizationConsole.stories.tsx",
    ],
    rationale:
      "The direct Button stories import the exact production component and specify official component-token variants and states, compact and touch-safe sizing, loading/disabled behavior, icon naming, form defaults, keyboard focus, and representative brand themes. Four additional production-composition stories exercise the same public export in cards, onboarding, account, and stakeholder-tool contexts.",
  },
};

export default metadata;
