export { ArrowSquareOutIcon as ExternalLink } from "@phosphor-icons/react/dist/ssr/ArrowSquareOut";
export { BellIcon as Bell } from "@phosphor-icons/react/dist/ssr/Bell";
export { BookmarkSimpleIcon as Bookmark } from "@phosphor-icons/react/dist/ssr/BookmarkSimple";
export { BookOpenTextIcon as BookOpenText } from "@phosphor-icons/react/dist/ssr/BookOpenText";
export { CalendarBlankIcon as CalendarBlank } from "@phosphor-icons/react/dist/ssr/CalendarBlank";
export { CameraIcon as Camera } from "@phosphor-icons/react/dist/ssr/Camera";
export { CarIcon as Car } from "@phosphor-icons/react/dist/ssr/Car";
export { CaretDownIcon as ChevronDown, CaretDownIcon as ChevronDownIcon } from "@phosphor-icons/react/dist/ssr/CaretDown";
export { CaretLeftIcon as ChevronLeft, CaretLeftIcon as ChevronLeftIcon } from "@phosphor-icons/react/dist/ssr/CaretLeft";
export { CaretRightIcon as ChevronRight, CaretRightIcon as ChevronRightIcon } from "@phosphor-icons/react/dist/ssr/CaretRight";
export { CaretUpIcon as ChevronUpIcon } from "@phosphor-icons/react/dist/ssr/CaretUp";
export { ChatCircleIcon as MessageCircle } from "@phosphor-icons/react/dist/ssr/ChatCircle";
export { CheckIcon as Check, CheckIcon as CheckIcon } from "@phosphor-icons/react/dist/ssr/Check";
export { CheckCircleIcon as CheckCircle2 } from "@phosphor-icons/react/dist/ssr/CheckCircle";
export { ChefHatIcon as ChefHat } from "@phosphor-icons/react/dist/ssr/ChefHat";
export { CircleIcon as Circle } from "@phosphor-icons/react/dist/ssr/Circle";
export { ClockIcon as Clock } from "@phosphor-icons/react/dist/ssr/Clock";
export { CompassIcon as Compass } from "@phosphor-icons/react/dist/ssr/Compass";
export { CurrencyDollarIcon as DollarSign } from "@phosphor-icons/react/dist/ssr/CurrencyDollar";
export { DownloadSimpleIcon as Download } from "@phosphor-icons/react/dist/ssr/DownloadSimple";
export { DotsThreeIcon as DotsThree } from "@phosphor-icons/react/dist/ssr/DotsThree";
export { EnvelopeSimpleIcon as Mail } from "@phosphor-icons/react/dist/ssr/EnvelopeSimple";
export { EyeSlashIcon as EyeOff } from "@phosphor-icons/react/dist/ssr/EyeSlash";
export { FireIcon as Flame } from "@phosphor-icons/react/dist/ssr/Fire";
export { FolderPlusIcon as FolderPlus } from "@phosphor-icons/react/dist/ssr/FolderPlus";
export { GearIcon as Settings } from "@phosphor-icons/react/dist/ssr/Gear";
export { HandbagIcon as ShoppingBag } from "@phosphor-icons/react/dist/ssr/Handbag";
export { HeadphonesIcon as Headphones } from "@phosphor-icons/react/dist/ssr/Headphones";
export { HeartIcon as Heart } from "@phosphor-icons/react/dist/ssr/Heart";
export { ImageIcon as ImageIcon } from "@phosphor-icons/react/dist/ssr/Image";
export { InfoIcon as Info } from "@phosphor-icons/react/dist/ssr/Info";
export { LightningIcon as Zap } from "@phosphor-icons/react/dist/ssr/Lightning";
export { ListIcon as Menu } from "@phosphor-icons/react/dist/ssr/List";
export { LockIcon as Lock } from "@phosphor-icons/react/dist/ssr/Lock";
export { MagnifyingGlassIcon as Search } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
export { MapPinIcon as MapPin } from "@phosphor-icons/react/dist/ssr/MapPin";
export { MoonIcon as Moon } from "@phosphor-icons/react/dist/ssr/Moon";
export { NewspaperIcon as Newspaper } from "@phosphor-icons/react/dist/ssr/Newspaper";
export { PaperPlaneTiltIcon as Send } from "@phosphor-icons/react/dist/ssr/PaperPlaneTilt";
export { PauseIcon as Pause } from "@phosphor-icons/react/dist/ssr/Pause";
export { PlayIcon as Play } from "@phosphor-icons/react/dist/ssr/Play";
export { PlusIcon as Plus } from "@phosphor-icons/react/dist/ssr/Plus";
export { PlusCircleIcon as CirclePlus } from "@phosphor-icons/react/dist/ssr/PlusCircle";
export { ShareNetworkIcon as Share2 } from "@phosphor-icons/react/dist/ssr/ShareNetwork";
export { SpeakerHighIcon as Volume2 } from "@phosphor-icons/react/dist/ssr/SpeakerHigh";
export { SpeakerSlashIcon as VolumeX } from "@phosphor-icons/react/dist/ssr/SpeakerSlash";
export { ShieldIcon as Shield } from "@phosphor-icons/react/dist/ssr/Shield";
export { SignOutIcon as LogOut } from "@phosphor-icons/react/dist/ssr/SignOut";
export { SlidersHorizontalIcon as SlidersHorizontal } from "@phosphor-icons/react/dist/ssr/SlidersHorizontal";
export { SparkleIcon as Sparkles } from "@phosphor-icons/react/dist/ssr/Sparkle";
export { SpinnerGapIcon as SpinnerGap } from "@phosphor-icons/react/dist/ssr/SpinnerGap";
export { StarIcon as Star } from "@phosphor-icons/react/dist/ssr/Star";
export { SunIcon as Sun } from "@phosphor-icons/react/dist/ssr/Sun";
export { TagIcon as Tag } from "@phosphor-icons/react/dist/ssr/Tag";
export { ThumbsUpIcon as ThumbsUp } from "@phosphor-icons/react/dist/ssr/ThumbsUp";
export { TrashIcon as Trash2 } from "@phosphor-icons/react/dist/ssr/Trash";
export { TrendUpIcon as TrendingUp } from "@phosphor-icons/react/dist/ssr/TrendUp";
export { UserIcon as User } from "@phosphor-icons/react/dist/ssr/User";
export { UserCircleIcon as CircleUserRound } from "@phosphor-icons/react/dist/ssr/UserCircle";
export { WarningIcon as TriangleAlert } from "@phosphor-icons/react/dist/ssr/Warning";
export { WrenchIcon as Wrench } from "@phosphor-icons/react/dist/ssr/Wrench";
export { XIcon as X } from "@phosphor-icons/react/dist/ssr/X";
export { XCircleIcon as CircleX } from "@phosphor-icons/react/dist/ssr/XCircle";

export type { Icon as PhosphorIcon } from "@phosphor-icons/react";
