// Auto-generated by scripts/sync-from-pencil.ts — do not edit manually
// Source: hearst-brands.pen | Synced: 2026-03-08T17:47:36.282Z

export interface BrandTheme {
  name: string;
  slug: string;
  colors: Record<string, string>;
  fontDefault: string;
  fontSecondary: string;
}

export const brands: BrandTheme[] = [
  {
    name: "White Label",
    slug: "white-label",
    colors: { "1": "#000000", "2": "#ffffff", "3": "#ffffff", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Autoweek",
    slug: "autoweek",
    colors: { "1": "#ffc84e", "2": "#eb3135", "3": "#2c6f74", "4": "#e96c28", "5": "#dae5d3", "6": "#f8f4f5" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Best Products",
    slug: "best-products",
    colors: { "1": "#1c1c9b", "2": "#e22d21", "3": "#1a847f", "4": "#24adcc", "5": "#f8e4dd", "6": "#eaf6f6" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Bicycling",
    slug: "bicycling",
    colors: { "1": "#067ea7", "2": "#f8d811", "3": "#EF4129", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Biography",
    slug: "biography",
    colors: { "1": "#a00000", "2": "#ffffff", "3": "#ffffff", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Car and Driver",
    slug: "car-and-driver",
    colors: { "1": "#1B5F8A", "2": "#00A4DB", "3": "#D2232A", "4": "#DBCA8B", "5": "#607D8B", "6": "#F1F7F7" },
    fontDefault: "Inter",
    fontSecondary: "Barlow Condensed",
  },
  {
    name: "Cosmopolitan",
    slug: "cosmopolitan",
    colors: { "1": "#d70000", "2": "#F6D3E5", "3": "#ffffff", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "Basis Grotesque Pro",
    fontSecondary: "Chronicle Display",
  },
  {
    name: "Country Living",
    slug: "country-living",
    colors: { "1": "#0a5c80", "2": "#cde5f0", "3": "#fff9ed", "4": "#3e93c3", "5": "#78756b", "6": "#9ecde1" },
    fontDefault: "Montserrat",
    fontSecondary: "PlayfairDisplay",
  },
  {
    name: "Delish",
    slug: "delish",
    colors: { "1": "#004685", "2": "#ffc035", "3": "#ff553e", "4": "#adcf21", "5": "#66cecf", "6": "#c6e9f0" },
    fontDefault: "TT Commons Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "ELLE",
    slug: "elle",
    colors: { "1": "#000000", "2": "#f5f5f4", "3": "#f0ede6", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "Neue Haas Unica Pro",
    fontSecondary: "Modern MT Pro",
  },
  {
    name: "ELLE Decor",
    slug: "elle-decor",
    colors: { "1": "#3777bc", "2": "#ffffff", "3": "#ffffff", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Esquire",
    slug: "esquire",
    colors: { "1": "#ff3a30", "2": "#f5f6f8", "3": "#15263d", "4": "#ff5a52", "5": "#e00b00", "6": "#ececec" },
    fontDefault: "Lausanne",
    fontSecondary: "PlayFair",
  },
  {
    name: "Good Housekeeping",
    slug: "good-housekeeping",
    colors: { "1": "#53c2be", "2": "#198294", "3": "#125c68", "4": "#f8f3f4", "5": "#9e3326", "6": "#d24432" },
    fontDefault: "Barlow Semi Condensed",
    fontSecondary: "Shippori Mincho",
  },
  {
    name: "Harper's BAZAAR",
    slug: "harpers-bazaar",
    colors: { "1": "#000000", "2": "#aa0703", "3": "#ff0000", "4": "#77747b", "5": "#ff5e5e", "6": "#ffffff" },
    fontDefault: "Helvetica Now Text",
    fontSecondary: "NewParis Text",
  },
  {
    name: "House Beautiful",
    slug: "house-beautiful",
    colors: { "1": "#242d39", "2": "#fbfafa", "3": "#f5f2ee", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "Visuelt Pro",
    fontSecondary: "Apparel Display",
  },
  {
    name: "Men's Health",
    slug: "mens-health",
    colors: { "1": "#d2232e", "2": "#fff200", "3": "#202020", "4": "#696969", "5": "#878787", "6": "#ffffff" },
    fontDefault: "Manrope",
    fontSecondary: "SF Pro",
  },
  {
    name: "Oprah Daily",
    slug: "oprah-daily",
    colors: { "1": "#e61957", "2": "#166534", "3": "#bef264", "4": "#fde047", "5": "#4a044e", "6": "#bae6fd" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Popular Mechanics",
    slug: "popular-mechanics",
    colors: { "1": "#1c6a65", "2": "#f04e3e", "3": "#fef837", "4": "#595959", "5": "#414141", "6": "#ececec" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Prevention",
    slug: "prevention",
    colors: { "1": "#44c1c5", "2": "#eaf4f5", "3": "#fcd029", "4": "#33a0a3", "5": "#088092", "6": "#ffffff" },
    fontDefault: "Poppins",
    fontSecondary: "SF Pro",
  },
  {
    name: "Redbook",
    slug: "redbook",
    colors: { "1": "#d30c4f", "2": "#69dcbf", "3": "#b2003c", "4": "#f8bbd0", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Road & Track",
    slug: "road-and-track",
    colors: { "1": "#434343", "2": "#1b1a1a", "3": "#b4b3b3", "4": "#ffffff", "5": "#668892", "6": "#bb322f" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Runner's World",
    slug: "runners-world",
    colors: { "1": "#59e7ed", "2": "#ff7d46", "3": "#17d0d8", "4": "#dffafc", "5": "#cc3d00", "6": "#b2cccb" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Seventeen",
    slug: "seventeen",
    colors: { "1": "#ff92de", "2": "#eeffae", "3": "#f1dce1", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "The Pioneer Woman",
    slug: "the-pioneer-woman",
    colors: { "1": "#8B376C", "2": "#F4EDD8", "3": "#242424", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "Livvic",
    fontSecondary: "Petrona",
  },
  {
    name: "Town & Country",
    slug: "town-and-country",
    colors: { "1": "#9a0500", "2": "#030929", "3": "#f1f2f4", "4": "#092958", "5": "#F1F6FE", "6": "#ffffff" },
    fontDefault: "Montserrat",
    fontSecondary: "NewParis Text",
  },
  {
    name: "Veranda",
    slug: "veranda",
    colors: { "1": "#f3ead9", "2": "#ffffff", "3": "#ffffff", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Woman's Day",
    slug: "womans-day",
    colors: { "1": "#683d85", "2": "#d80900", "3": "#ee4741", "4": "#ffffff", "5": "#ffffff", "6": "#ffffff" },
    fontDefault: "SF Pro",
    fontSecondary: "SF Pro",
  },
  {
    name: "Women's Health",
    slug: "womens-health",
    colors: { "1": "#1d4ed8", "2": "#ebff7c", "3": "#14b8a6", "4": "#e9d5ff", "5": "#f9a8d4", "6": "#ffedd5" },
    fontDefault: "Altone",
    fontSecondary: "Apparel",
  },
];