import type { CSSProperties } from "react";

export type HearstPlusCssVars = CSSProperties & Record<`--${string}`, string | number>;

export const hearstPlusLightVars: HearstPlusCssVars = {
  "--background": "#F4F2EE",
  "--foreground": "var(--palette-content-default, #121212)",
  "--card": "var(--component-card-background-default, var(--palette-background-default, #ffffff))",
  "--card-foreground": "var(--palette-content-default, #121212)",
  "--popover": "var(--component-modal-background-primary-default, var(--card))",
  "--popover-foreground": "var(--card-foreground)",
  "--muted": "var(--palette-background-subtle, #ededed)",
  "--muted-foreground": "var(--palette-content-subtle, #757575)",
  "--secondary": "var(--palette-background-subtle, #ededed)",
  "--secondary-foreground": "var(--palette-content-default, #121212)",
  "--accent": "var(--palette-background-subtle-brand, var(--muted))",
  "--accent-foreground": "var(--palette-content-default, #121212)",
  "--border": "var(--component-card-border-default, var(--palette-neutral-300, #d6d6d6))",
  "--input": "var(--component-input-border-color-primary-outlined-default, var(--border))",
  "--primary": "var(--palette-background-brand, #384959)",
  "--primary-foreground": "#ffffff",
  "--ring": "#BDDDFC",
  "--radius": "var(--border-radius-xs, 8px)",

  "--hp-font-ui": "\"Inter\", system-ui, sans-serif",
  "--hp-font-headline": "var(--font-hearst-plus-headline, \"Newsreader\", Georgia, serif)",
  "--hp-font-headline-weight": 700,

  "--hp-background": "var(--background)",
  "--hp-nav": "var(--primary)",
  "--hp-nav-translucent": "color-mix(in oklab, var(--primary) 94%, transparent)",
  "--hp-strip": "var(--card)",
  "--hp-surface-deep": "var(--foreground)",
  "--hp-surface-low": "var(--muted)",
  "--hp-surface": "var(--card)",
  "--hp-control": "color-mix(in oklab, var(--foreground) 4%, var(--background) 96%)",
  "--hp-control-hover": "color-mix(in oklab, var(--foreground) 7%, var(--background) 93%)",
  "--hp-chip": "color-mix(in oklab, var(--foreground) 3%, var(--background) 97%)",
  "--hp-chip-border": "color-mix(in oklab, var(--border) 72%, var(--background) 28%)",
  "--hp-border": "var(--border)",
  "--hp-border-strong": "color-mix(in oklab, var(--border) 55%, var(--foreground) 45%)",

  "--hp-logo": "#BDDDFC",
  "--hp-nav-text": "#ffffff",
  "--hp-text-headline": "var(--foreground)",
  "--hp-text-primary": "var(--foreground)",
  "--hp-text-ui": "color-mix(in oklab, var(--foreground) 78%, var(--background) 22%)",
  "--hp-text-chip": "color-mix(in oklab, var(--foreground) 62%, var(--background) 38%)",
  "--hp-text-secondary": "var(--muted-foreground)",
  "--hp-text-muted": "color-mix(in oklab, var(--muted-foreground) 80%, var(--background) 20%)",
  "--hp-text-faint": "color-mix(in oklab, var(--muted-foreground) 68%, transparent)",
  "--hp-ink-on-light": "var(--palette-content-default, #222222)",

  "--hp-primary": "var(--primary)",
  "--hp-primary-hover": "color-mix(in oklab, #384959 82%, #BDDDFC 18%)",
  "--hp-primary-soft": "#BDDDFC",
  "--hp-primary-soft-hover": "color-mix(in oklab, #BDDDFC 86%, #384959 14%)",
  "--hp-friendly-accent": "var(--component-chip-background-neutral-selected, #BDDDFC)",
  "--hp-friendly-accent-hover": "color-mix(in oklab, var(--component-chip-background-neutral-selected, #BDDDFC) 86%, #384959 14%)",
  "--hp-friendly-accent-border": "var(--component-chip-border-neutral-selected, #384959)",
  "--hp-friendly-accent-text": "var(--component-chip-content-neutral-selected, #384959)",
  "--hp-focus": "var(--ring)",
  "--hp-signal": "#384959",
  "--hp-action": "var(--component-button-background-primary-solid-default, #384959)",
  "--hp-action-hover": "var(--component-button-background-primary-solid-hover, color-mix(in oklab, #384959 82%, #BDDDFC 18%))",
  "--hp-action-active": "var(--component-button-background-primary-solid-active, color-mix(in oklab, #384959 90%, #BDDDFC 10%))",
  "--hp-action-text": "#ffffff",
  "--hp-action-soft": "#BDDDFC",
  "--hp-action-soft-hover": "color-mix(in oklab, #BDDDFC 86%, #384959 14%)",
  "--hp-action-soft-text": "#384959",
  "--hp-flag-bg": "rgba(255, 255, 255, 0.76)",
  "--hp-flag-border": "rgba(18, 18, 18, 0.08)",
  "--hp-flag-text": "#37423e",
  "--hp-rank-bg": "color-mix(in oklab, var(--primary) 11%, var(--background) 89%)",
  "--hp-rank-border": "#BDDDFC",
  "--hp-rank-text": "color-mix(in oklab, var(--primary) 76%, var(--foreground) 24%)",

  "--hp-food": "#BDDDFC",
  "--hp-wellness": "#BDDDFC",
  "--hp-cars": "#384959",
  "--hp-home": "#BDDDFC",
  "--hp-style": "#384959",
  "--hp-entertainment": "#384959",
  "--hp-technology": "#384959",
  "--hp-positive": "#384959",
  "--hp-positive-bg": "color-mix(in oklab, #BDDDFC 28%, var(--background) 72%)",

  "--hp-radius-card": "var(--radius)",
  "--hp-radius-pill": "999px",
  "--hp-shadow-card": "none",
  "--hp-shadow-modal": "0 8px 20px rgba(0, 0, 0, 0.3)",
  "--hp-motion-fast": "160ms",
  "--hp-motion-standard": "240ms",
};

export const hearstPlusDarkVars: HearstPlusCssVars = {
  ...hearstPlusLightVars,
  "--background": "#0d1014",
  "--foreground": "#f8fbff",
  "--card": "#181b20",
  "--card-foreground": "#f4f7fb",
  "--muted": "#20242b",
  "--muted-foreground": "#aab5c3",
  "--secondary": "#20242b",
  "--secondary-foreground": "#f4f7fb",
  "--accent": "#232a33",
  "--accent-foreground": "#dbe3ed",
  "--border": "rgba(255, 255, 255, 0.1)",
  "--input": "rgba(255, 255, 255, 0.15)",
  "--ring": "#BDDDFC",

  "--hp-background": "var(--background)",
  "--hp-nav": "#384959",
  "--hp-nav-translucent": "rgba(56, 73, 89, 0.96)",
  "--hp-strip": "#14171c",
  "--hp-surface-deep": "#0f1115",
  "--hp-surface-low": "var(--card)",
  "--hp-surface": "var(--card)",
  "--hp-control": "var(--muted)",
  "--hp-control-hover": "#2a3038",
  "--hp-chip": "color-mix(in oklab, var(--foreground) 7%, var(--background) 93%)",
  "--hp-chip-border": "rgba(255, 255, 255, 0.08)",
  "--hp-border": "var(--border)",
  "--hp-border-strong": "rgba(255, 255, 255, 0.2)",

  "--hp-logo": "#BDDDFC",
  "--hp-nav-text": "#ffffff",
  "--hp-text-headline": "#f8fbff",
  "--hp-text-primary": "#f4f7fb",
  "--hp-text-ui": "#dbe3ed",
  "--hp-text-chip": "#cad5e2",
  "--hp-text-secondary": "#aab5c3",
  "--hp-text-muted": "#95a0ad",
  "--hp-text-faint": "rgba(255, 255, 255, 0.52)",

  "--hp-primary": "#BDDDFC",
  "--hp-primary-hover": "#BDDDFC",
  "--hp-primary-soft": "#253746",
  "--hp-primary-soft-hover": "#384959",
  "--hp-friendly-accent": "color-mix(in oklab, #384959 74%, #0d1014 26%)",
  "--hp-friendly-accent-hover": "color-mix(in oklab, #384959 88%, #0d1014 12%)",
  "--hp-friendly-accent-border": "#BDDDFC",
  "--hp-friendly-accent-text": "#BDDDFC",
  "--hp-focus": "#BDDDFC",
  "--hp-signal": "#BDDDFC",
  "--hp-action": "#BDDDFC",
  "--hp-action-hover": "color-mix(in oklab, #BDDDFC 86%, #384959 14%)",
  "--hp-action-active": "color-mix(in oklab, #BDDDFC 78%, #384959 22%)",
  "--hp-action-text": "#384959",
  "--hp-action-soft": "#BDDDFC",
  "--hp-action-soft-hover": "color-mix(in oklab, #BDDDFC 86%, #384959 14%)",
  "--hp-action-soft-text": "#384959",
  "--hp-flag-bg": "rgba(255, 255, 255, 0.78)",
  "--hp-flag-border": "rgba(255, 255, 255, 0.18)",
  "--hp-flag-text": "#1f2933",
  "--hp-rank-bg": "#253746",
  "--hp-rank-border": "#BDDDFC",
  "--hp-rank-text": "#BDDDFC",
  "--hp-positive": "#BDDDFC",
  "--hp-positive-bg": "color-mix(in oklab, #384959 74%, #0d1014 26%)",

  "--hp-shadow-card": "0 4px 14px rgba(0, 0, 0, 0.22)",
};
