import { brands, type BrandTheme } from "./brands";

export const hearstPlusTheme: BrandTheme = {
  name: "Hearst Autos",
  slug: "hearst-plus",
  colors: {
    "1": "#1B5F8A",
    "2": "#D8EAF4",
    "3": "#0E3F61",
    "4": "#B7D6E8",
    "5": "#F3F7FA",
    "6": "#E8F1F6",
    "7": "#102A3A",
    "8": "#ffffff",
    "9": "#2878A8",
    "10": "#7699AD",
    "11": "#121212",
    "12": "#ffffff",
    "13": "#ffffff",
    "14": "#ffffff",
  },
  fontDefault: "Inter",
  fontSecondary: "Inter",
  fontHeadline: "Barlow Condensed",
  fontHeadlineWeight: 700,
  semanticColors: {
    "palette-background-brand": "#1B5F8A",
    "palette-background-brand-active": "#0E3F61",
    "palette-background-brand-hover": "#154E72",
    "palette-background-default": "#ffffff",
    "palette-background-default-link": "#1B5F8A",
    "palette-background-default-link-hover": "#0E3F61",
    "palette-background-knockout": "#121212",
    "palette-background-knockout-hover": "#292929",
    "palette-background-page": "#F3F7FA",
    "palette-background-subtle": "#ededed",
    "palette-background-subtle-brand": "#D8EAF4",
    "palette-background-utility": "#D8EAF4",
    "palette-content-brand": "#1B5F8A",
    "palette-content-brand-active": "#0E3F61",
    "palette-content-brand-hover": "#154E72",
    "palette-content-default": "#121212",
    "palette-content-default-active": "#3b3b3b",
    "palette-content-default-hover": "#292929",
    "palette-content-default-link": "#1B5F8A",
    "palette-content-default-link-hover": "#0E3F61",
    "palette-content-knockout-hover": "#ededed",
    "palette-content-subtle": "#5F6B7A",
  },
  componentTokens: {
    "component-card-background-default": "#ffffff",
    "component-card-background-neutral": "#ededed",
    "component-card-border-default": "#d6d6d6",
    "component-button-background-primary-solid-default": "#1B5F8A",
    "component-button-background-primary-solid-hover": "#154E72",
    "component-button-background-primary-solid-active": "#0E3F61",
    "component-button-background-primary-outlined-default": "#ffffff",
    "component-button-background-primary-outlined-hover": "#D8EAF4",
    "component-button-background-neutral-outlined-default": "#ffffff",
    "component-button-background-neutral-outlined-hover": "#ededed",
    "component-button-border-neutral-outlined-default": "#d6d6d6",
    "component-button-content-neutral-outlined-default": "#121212",
    "component-chip-background-neutral-default": "#ffffff",
    "component-chip-background-neutral-hover": "#ededed",
    "component-chip-background-neutral-selected": "#D8EAF4",
    "component-chip-border-neutral-default": "#d6d6d6",
    "component-chip-border-neutral-hover": "#121212",
    "component-chip-border-neutral-selected": "#1B5F8A",
    "component-chip-content-neutral-default": "#121212",
    "component-chip-content-neutral-hover": "#121212",
    "component-chip-content-neutral-selected": "#1B5F8A",
    "component-input-border-color-primary-outlined-default": "#949494",
    "component-modal-background-primary-default": "#ffffff",
    "component-badge-background-primary": "#1B5F8A",
    "component-badge-content-primary": "#ffffff",
    "component-badge-radius-md": 8,
    "component-badge-radius-rounded": 64,
  },
};

export const lifestyleTheme: BrandTheme = {
  name: "Hearst Lifestyle",
  slug: "hearst-lifestyle",
  colors: {
    "1": "#7A2E57",
    "2": "#F7C6D9",
    "3": "#2E6F73",
    "4": "#F5A623",
    "5": "#F7EFE7",
    "6": "#E6F2EF",
    "7": "#1F2933",
    "8": "#ffffff",
    "9": "#C73E6B",
    "10": "#86A873",
    "11": "#121212",
    "12": "#ffffff",
    "13": "#ffffff",
    "14": "#ffffff",
  },
  fontDefault: "Inter",
  fontSecondary: "Newsreader",
  fontHeadline: "Newsreader",
  fontHeadlineWeight: 700,
  semanticColors: {
    "palette-background-brand": "#7A2E57",
    "palette-background-brand-active": "#55213E",
    "palette-background-brand-hover": "#653050",
    "palette-background-default": "#ffffff",
    "palette-background-default-link": "#7A2E57",
    "palette-background-default-link-hover": "#55213E",
    "palette-background-knockout": "#121212",
    "palette-background-knockout-hover": "#292929",
    "palette-background-page": "#F7EFE7",
    "palette-background-subtle": "#F4E6EE",
    "palette-background-subtle-brand": "#F7C6D9",
    "palette-background-utility": "#2E6F73",
    "palette-content-brand": "#7A2E57",
    "palette-content-brand-active": "#55213E",
    "palette-content-brand-hover": "#653050",
    "palette-content-default": "#121212",
    "palette-content-default-active": "#3b3b3b",
    "palette-content-default-hover": "#292929",
    "palette-content-default-link": "#7A2E57",
    "palette-content-default-link-hover": "#55213E",
    "palette-content-knockout-hover": "#ededed",
    "palette-content-subtle": "#667085",
  },
  componentTokens: {
    "component-card-background-default": "#ffffff",
    "component-card-background-neutral": "#F7EFE7",
    "component-card-border-default": "#E7D6DF",
    "component-button-background-primary-solid-default": "#7A2E57",
    "component-button-background-primary-solid-hover": "#653050",
    "component-button-background-primary-solid-active": "#55213E",
    "component-button-background-primary-outlined-default": "#ffffff",
    "component-button-background-primary-outlined-hover": "#F7C6D9",
    "component-button-background-neutral-outlined-default": "#ffffff",
    "component-button-background-neutral-outlined-hover": "#F7EFE7",
    "component-button-border-neutral-outlined-default": "#E7D6DF",
    "component-button-content-neutral-outlined-default": "#121212",
    "component-chip-background-neutral-default": "#ffffff",
    "component-chip-background-neutral-hover": "#F7EFE7",
    "component-chip-background-neutral-selected": "#F7C6D9",
    "component-chip-border-neutral-default": "#E7D6DF",
    "component-chip-border-neutral-hover": "#7A2E57",
    "component-chip-border-neutral-selected": "#7A2E57",
    "component-chip-content-neutral-default": "#121212",
    "component-chip-content-neutral-hover": "#121212",
    "component-chip-content-neutral-selected": "#7A2E57",
    "component-input-border-color-primary-outlined-default": "#A08A96",
    "component-modal-background-primary-default": "#ffffff",
    "component-badge-background-primary": "#7A2E57",
    "component-badge-content-primary": "#ffffff",
    "component-badge-radius-md": 8,
    "component-badge-radius-rounded": 64,
  },
};

export const fluxTheme: BrandTheme = {
  ...lifestyleTheme,
  name: "Hearst Flux",
  slug: "hearst-flux",
  fontHeadline: "Modern MT Pro",
  fontHeadlineWeight: 400,
  colors: {
    ...lifestyleTheme.colors,
    "1": "#000000",
    "2": "#EDEDED",
    "3": "#2B2B2B",
    "4": "#D6D6D6",
    "5": "#F7F7F7",
    "6": "#EFEFEF",
    "7": "#121212",
    "9": "#333333",
    "10": "#757575",
  },
  semanticColors: {
    ...lifestyleTheme.semanticColors,
    "palette-background-brand": "#000000",
    "palette-background-brand-active": "#121212",
    "palette-background-brand-hover": "#2B2B2B",
    "palette-background-default-link": "#000000",
    "palette-background-default-link-hover": "#2B2B2B",
    "palette-background-page": "#F7F7F7",
    "palette-background-subtle": "#EFEFEF",
    "palette-background-subtle-brand": "#EDEDED",
    "palette-background-utility": "#EDEDED",
    "palette-content-brand": "#000000",
    "palette-content-brand-active": "#121212",
    "palette-content-brand-hover": "#2B2B2B",
    "palette-content-default-link": "#000000",
    "palette-content-default-link-hover": "#2B2B2B",
  },
  componentTokens: {
    ...lifestyleTheme.componentTokens,
    "component-card-background-neutral": "#F7F7F7",
    "component-card-border-default": "#D6D6D6",
    "component-button-background-primary-solid-default": "#000000",
    "component-button-background-primary-solid-hover": "#2B2B2B",
    "component-button-background-primary-solid-active": "#121212",
    "component-button-background-primary-outlined-hover": "#EDEDED",
    "component-button-border-neutral-outlined-default": "#D6D6D6",
    "component-chip-background-neutral-hover": "#F7F7F7",
    "component-chip-background-neutral-selected": "#EDEDED",
    "component-chip-border-neutral-default": "#D6D6D6",
    "component-chip-border-neutral-hover": "#000000",
    "component-chip-border-neutral-selected": "#000000",
    "component-chip-content-neutral-selected": "#000000",
    "component-input-border-color-primary-outlined-default": "#757575",
    "component-badge-background-primary": "#000000",
  },
};

export const ewTheme: BrandTheme = {
  ...lifestyleTheme,
  name: "Hearst E&W",
  slug: "hearst-ew",
  fontHeadline: "Barlow Semi Condensed",
  fontHeadlineWeight: 800,
  fontHeadlineStretch: "normal",
  colors: {
    ...lifestyleTheme.colors,
    "1": "#E50022",
    "2": "#FFE0E4",
    "3": "#970017",
    "4": "#FFC2CB",
    "5": "#FFF5F6",
    "6": "#F7F7F7",
    "7": "#231F20",
    "9": "#B8001B",
    "10": "#8A5A61",
  },
  semanticColors: {
    ...lifestyleTheme.semanticColors,
    "palette-background-brand": "#E50022",
    "palette-background-brand-active": "#970017",
    "palette-background-brand-hover": "#B8001B",
    "palette-background-default-link": "#E50022",
    "palette-background-default-link-hover": "#970017",
    "palette-background-page": "#FFF5F6",
    "palette-background-subtle": "#F7F7F7",
    "palette-background-subtle-brand": "#FFE0E4",
    "palette-background-utility": "#FFE0E4",
    "palette-content-brand": "#E50022",
    "palette-content-brand-active": "#970017",
    "palette-content-brand-hover": "#B8001B",
    "palette-content-default-link": "#E50022",
    "palette-content-default-link-hover": "#970017",
  },
  componentTokens: {
    ...lifestyleTheme.componentTokens,
    "component-card-background-neutral": "#FFF5F6",
    "component-card-border-default": "#E7D6DF",
    "component-button-background-primary-solid-default": "#E50022",
    "component-button-background-primary-solid-hover": "#B8001B",
    "component-button-background-primary-solid-active": "#970017",
    "component-button-background-primary-outlined-hover": "#FFE0E4",
    "component-chip-background-neutral-hover": "#FFF5F6",
    "component-chip-background-neutral-selected": "#FFE0E4",
    "component-chip-border-neutral-hover": "#E50022",
    "component-chip-border-neutral-selected": "#E50022",
    "component-chip-content-neutral-selected": "#E50022",
    "component-input-border-color-primary-outlined-default": "#8A5A61",
    "component-badge-background-primary": "#E50022",
  },
};

export const hearstAllTheme: BrandTheme = {
  ...lifestyleTheme,
  name: "Hearst Magazines",
  slug: "hearst-all",
  fontSecondary: "Inter",
  fontHeadline: "Newsreader",
  fontHeadlineWeight: 700,
  colors: {
    ...lifestyleTheme.colors,
    "1": "#2B6FAF",
    "2": "#DCEBFA",
    "3": "#174C7D",
    "4": "#9FC5E8",
    "5": "#F4F8FC",
    "6": "#EDF4FB",
    "7": "#102A43",
    "9": "#1F65A6",
    "10": "#6A92B7",
  },
  semanticColors: {
    ...lifestyleTheme.semanticColors,
    "palette-background-brand": "#2B6FAF",
    "palette-background-brand-active": "#174C7D",
    "palette-background-brand-hover": "#1F65A6",
    "palette-background-default-link": "#2B6FAF",
    "palette-background-default-link-hover": "#174C7D",
    "palette-background-page": "#F4F8FC",
    "palette-background-subtle": "#EDF4FB",
    "palette-background-subtle-brand": "#DCEBFA",
    "palette-background-utility": "#DCEBFA",
    "palette-content-brand": "#2B6FAF",
    "palette-content-brand-active": "#174C7D",
    "palette-content-brand-hover": "#1F65A6",
    "palette-content-default-link": "#2B6FAF",
    "palette-content-default-link-hover": "#174C7D",
    "palette-content-subtle": "#5F6B7A",
  },
  componentTokens: {
    ...lifestyleTheme.componentTokens,
    "component-card-background-neutral": "#F4F8FC",
    "component-card-border-default": "#C7D9EA",
    "component-button-background-primary-solid-default": "#2B6FAF",
    "component-button-background-primary-solid-hover": "#1F65A6",
    "component-button-background-primary-solid-active": "#174C7D",
    "component-button-background-primary-outlined-hover": "#DCEBFA",
    "component-chip-background-neutral-hover": "#F4F8FC",
    "component-chip-background-neutral-selected": "#DCEBFA",
    "component-chip-border-neutral-hover": "#2B6FAF",
    "component-chip-border-neutral-selected": "#2B6FAF",
    "component-chip-content-neutral-selected": "#2B6FAF",
    "component-input-border-color-primary-outlined-default": "#6A92B7",
    "component-badge-background-primary": "#2B6FAF",
  },
};

export const themeOptions: BrandTheme[] = [hearstAllTheme, hearstPlusTheme, lifestyleTheme, fluxTheme, ewTheme, ...brands];
