import { brands, type BrandTheme } from "./brands";

export const hearstPlusTheme: BrandTheme = {
  name: "AUTOS",
  slug: "hearst-plus",
  colors: {
    "1": "#384959",
    "2": "#BDDDFC",
    "3": "#384959",
    "4": "#BDDDFC",
    "5": "#384959",
    "6": "#BDDDFC",
    "7": "#384959",
    "8": "#BDDDFC",
    "9": "#384959",
    "10": "#BDDDFC",
    "11": "#384959",
    "12": "#BDDDFC",
    "13": "#384959",
    "14": "#BDDDFC",
  },
  fontDefault: "Inter",
  fontSecondary: "Inter",
  fontHeadline: "Newsreader",
  fontHeadlineWeight: 700,
  semanticColors: {
    "palette-background-brand": "#384959",
    "palette-background-brand-active": "#2d3b49",
    "palette-background-brand-hover": "#384959",
    "palette-background-default": "#ffffff",
    "palette-background-default-link": "#384959",
    "palette-background-default-link-hover": "#384959",
    "palette-background-knockout": "#121212",
    "palette-background-knockout-hover": "#292929",
    "palette-background-page": "#F4F2EE",
    "palette-background-subtle": "#ededed",
    "palette-background-subtle-brand": "#BDDDFC",
    "palette-background-utility": "#BDDDFC",
    "palette-content-brand": "#384959",
    "palette-content-brand-active": "#2d3b49",
    "palette-content-brand-hover": "#384959",
    "palette-content-default": "#121212",
    "palette-content-default-active": "#3b3b3b",
    "palette-content-default-hover": "#292929",
    "palette-content-default-link": "#384959",
    "palette-content-default-link-hover": "#384959",
    "palette-content-knockout-hover": "#ededed",
    "palette-content-subtle": "#757575",
  },
  componentTokens: {
    "component-card-background-default": "#ffffff",
    "component-card-background-neutral": "#ededed",
    "component-card-border-default": "#d6d6d6",
    "component-button-background-primary-solid-default": "#384959",
    "component-button-background-primary-solid-hover": "#384959",
    "component-button-background-primary-solid-active": "#384959",
    "component-button-background-primary-outlined-default": "#ffffff",
    "component-button-background-primary-outlined-hover": "#BDDDFC",
    "component-button-background-neutral-outlined-default": "#ffffff",
    "component-button-background-neutral-outlined-hover": "#ededed",
    "component-button-border-neutral-outlined-default": "#d6d6d6",
    "component-button-content-neutral-outlined-default": "#121212",
    "component-chip-background-neutral-default": "#ffffff",
    "component-chip-background-neutral-hover": "#ededed",
    "component-chip-background-neutral-selected": "#BDDDFC",
    "component-chip-border-neutral-default": "#d6d6d6",
    "component-chip-border-neutral-hover": "#121212",
    "component-chip-border-neutral-selected": "#384959",
    "component-chip-content-neutral-default": "#121212",
    "component-chip-content-neutral-hover": "#121212",
    "component-chip-content-neutral-selected": "#384959",
    "component-input-border-color-primary-outlined-default": "#949494",
    "component-modal-background-primary-default": "#ffffff",
    "component-badge-background-primary": "#384959",
    "component-badge-content-primary": "#ffffff",
    "component-badge-radius-md": 8,
    "component-badge-radius-rounded": 64,
  },
};

export const lifestyleTheme: BrandTheme = {
  name: "Hearst Lifestyle",
  slug: "hearst-lifestyle",
  colors: {
    "1": "#7A2E57",
    "2": "#F7C6D9",
    "3": "#2E6F73",
    "4": "#F5A623",
    "5": "#F7EFE7",
    "6": "#E6F2EF",
    "7": "#1F2933",
    "8": "#ffffff",
    "9": "#C73E6B",
    "10": "#86A873",
    "11": "#121212",
    "12": "#ffffff",
    "13": "#ffffff",
    "14": "#ffffff",
  },
  fontDefault: "Inter",
  fontSecondary: "Newsreader",
  fontHeadline: "Newsreader",
  fontHeadlineWeight: 700,
  semanticColors: {
    "palette-background-brand": "#7A2E57",
    "palette-background-brand-active": "#55213E",
    "palette-background-brand-hover": "#653050",
    "palette-background-default": "#ffffff",
    "palette-background-default-link": "#7A2E57",
    "palette-background-default-link-hover": "#55213E",
    "palette-background-knockout": "#121212",
    "palette-background-knockout-hover": "#292929",
    "palette-background-page": "#F7EFE7",
    "palette-background-subtle": "#F4E6EE",
    "palette-background-subtle-brand": "#F7C6D9",
    "palette-background-utility": "#2E6F73",
    "palette-content-brand": "#7A2E57",
    "palette-content-brand-active": "#55213E",
    "palette-content-brand-hover": "#653050",
    "palette-content-default": "#121212",
    "palette-content-default-active": "#3b3b3b",
    "palette-content-default-hover": "#292929",
    "palette-content-default-link": "#7A2E57",
    "palette-content-default-link-hover": "#55213E",
    "palette-content-knockout-hover": "#ededed",
    "palette-content-subtle": "#667085",
  },
  componentTokens: {
    "component-card-background-default": "#ffffff",
    "component-card-background-neutral": "#F7EFE7",
    "component-card-border-default": "#E7D6DF",
    "component-button-background-primary-solid-default": "#7A2E57",
    "component-button-background-primary-solid-hover": "#653050",
    "component-button-background-primary-solid-active": "#55213E",
    "component-button-background-primary-outlined-default": "#ffffff",
    "component-button-background-primary-outlined-hover": "#F7C6D9",
    "component-button-background-neutral-outlined-default": "#ffffff",
    "component-button-background-neutral-outlined-hover": "#F7EFE7",
    "component-button-border-neutral-outlined-default": "#E7D6DF",
    "component-button-content-neutral-outlined-default": "#121212",
    "component-chip-background-neutral-default": "#ffffff",
    "component-chip-background-neutral-hover": "#F7EFE7",
    "component-chip-background-neutral-selected": "#F7C6D9",
    "component-chip-border-neutral-default": "#E7D6DF",
    "component-chip-border-neutral-hover": "#7A2E57",
    "component-chip-border-neutral-selected": "#7A2E57",
    "component-chip-content-neutral-default": "#121212",
    "component-chip-content-neutral-hover": "#121212",
    "component-chip-content-neutral-selected": "#7A2E57",
    "component-input-border-color-primary-outlined-default": "#A08A96",
    "component-modal-background-primary-default": "#ffffff",
    "component-badge-background-primary": "#7A2E57",
    "component-badge-content-primary": "#ffffff",
    "component-badge-radius-md": 8,
    "component-badge-radius-rounded": 64,
  },
};

export const themeOptions: BrandTheme[] = [hearstPlusTheme, lifestyleTheme, ...brands];
