import { brands, type BrandTheme } from "./brands";

export const hearstPlusTheme: BrandTheme = {
  name: "Hearst Autos",
  slug: "hearst-plus",
  colors: {
    "1": "#245F86",
    "2": "#D8EAF4",
    "3": "#163F5A",
    "4": "#B7D6E8",
    "5": "#F3F7FA",
    "6": "#E8F1F6",
    "7": "#102A3A",
    "8": "#ffffff",
    "9": "#1D4F70",
    "10": "#7699AD",
    "11": "#121212",
    "12": "#ffffff",
    "13": "#ffffff",
    "14": "#ffffff",
  },
  fontDefault: "Inter",
  fontSecondary: "Inter",
  fontHeadline: "Barlow Condensed",
  fontHeadlineWeight: 700,
  semanticColors: {
    "palette-background-brand": "#245F86",
    "palette-background-brand-active": "#163F5A",
    "palette-background-brand-hover": "#1D4F70",
    "palette-background-default": "#ffffff",
    "palette-background-default-link": "#245F86",
    "palette-background-default-link-hover": "#163F5A",
    "palette-background-knockout": "#121212",
    "palette-background-knockout-hover": "#292929",
    "palette-background-page": "#F3F7FA",
    "palette-background-subtle": "#ededed",
    "palette-background-subtle-brand": "#D8EAF4",
    "palette-background-utility": "#D8EAF4",
    "palette-content-brand": "#245F86",
    "palette-content-brand-active": "#163F5A",
    "palette-content-brand-hover": "#1D4F70",
    "palette-content-default": "#121212",
    "palette-content-default-active": "#3b3b3b",
    "palette-content-default-hover": "#292929",
    "palette-content-default-link": "#245F86",
    "palette-content-default-link-hover": "#163F5A",
    "palette-content-knockout-hover": "#ededed",
    "palette-content-subtle": "#5F6B7A",
  },
  componentTokens: {
    "component-card-background-default": "#ffffff",
    "component-card-background-neutral": "#ededed",
    "component-card-border-default": "#d6d6d6",
    "component-button-background-primary-solid-default": "#245F86",
    "component-button-background-primary-solid-hover": "#1D4F70",
    "component-button-background-primary-solid-active": "#163F5A",
    "component-button-background-primary-outlined-default": "#ffffff",
    "component-button-background-primary-outlined-hover": "#D8EAF4",
    "component-button-background-neutral-outlined-default": "#ffffff",
    "component-button-background-neutral-outlined-hover": "#ededed",
    "component-button-border-neutral-outlined-default": "#d6d6d6",
    "component-button-content-neutral-outlined-default": "#121212",
    "component-chip-background-neutral-default": "#ffffff",
    "component-chip-background-neutral-hover": "#ededed",
    "component-chip-background-neutral-selected": "#D8EAF4",
    "component-chip-border-neutral-default": "#d6d6d6",
    "component-chip-border-neutral-hover": "#121212",
    "component-chip-border-neutral-selected": "#245F86",
    "component-chip-content-neutral-default": "#121212",
    "component-chip-content-neutral-hover": "#121212",
    "component-chip-content-neutral-selected": "#245F86",
    "component-input-border-color-primary-outlined-default": "#949494",
    "component-modal-background-primary-default": "#ffffff",
    "component-badge-background-primary": "#245F86",
    "component-badge-content-primary": "#ffffff",
    "component-badge-radius-md": 8,
    "component-badge-radius-rounded": 64,
  },
};

export const lifestyleTheme: BrandTheme = {
  name: "Hearst Lifestyle",
  slug: "hearst-lifestyle",
  colors: {
    "1": "#7A2E5D",
    "2": "#F7C6D9",
    "3": "#2E6F73",
    "4": "#F5A623",
    "5": "#F7EFE7",
    "6": "#E6F2EF",
    "7": "#1F2933",
    "8": "#ffffff",
    "9": "#C73E6B",
    "10": "#86A873",
    "11": "#121212",
    "12": "#ffffff",
    "13": "#ffffff",
    "14": "#ffffff",
  },
  fontDefault: "Inter",
  fontSecondary: "Newsreader",
  fontHeadline: "Newsreader",
  fontHeadlineWeight: 700,
  semanticColors: {
    "palette-background-brand": "#7A2E5D",
    "palette-background-brand-active": "#552142",
    "palette-background-brand-hover": "#663050",
    "palette-background-default": "#ffffff",
    "palette-background-default-link": "#7A2E5D",
    "palette-background-default-link-hover": "#552142",
    "palette-background-knockout": "#121212",
    "palette-background-knockout-hover": "#292929",
    "palette-background-page": "#F7EFE7",
    "palette-background-subtle": "#F4E6EE",
    "palette-background-subtle-brand": "#F7C6D9",
    "palette-background-utility": "#2E6F73",
    "palette-content-brand": "#7A2E5D",
    "palette-content-brand-active": "#552142",
    "palette-content-brand-hover": "#663050",
    "palette-content-default": "#121212",
    "palette-content-default-active": "#3b3b3b",
    "palette-content-default-hover": "#292929",
    "palette-content-default-link": "#7A2E5D",
    "palette-content-default-link-hover": "#552142",
    "palette-content-knockout-hover": "#ededed",
    "palette-content-subtle": "#667085",
  },
  componentTokens: {
    "component-card-background-default": "#ffffff",
    "component-card-background-neutral": "#F7EFE7",
    "component-card-border-default": "#E7D6DF",
    "component-button-background-primary-solid-default": "#7A2E5D",
    "component-button-background-primary-solid-hover": "#663050",
    "component-button-background-primary-solid-active": "#552142",
    "component-button-background-primary-outlined-default": "#ffffff",
    "component-button-background-primary-outlined-hover": "#F7C6D9",
    "component-button-background-neutral-outlined-default": "#ffffff",
    "component-button-background-neutral-outlined-hover": "#F7EFE7",
    "component-button-border-neutral-outlined-default": "#E7D6DF",
    "component-button-content-neutral-outlined-default": "#121212",
    "component-chip-background-neutral-default": "#ffffff",
    "component-chip-background-neutral-hover": "#F7EFE7",
    "component-chip-background-neutral-selected": "#F7C6D9",
    "component-chip-border-neutral-default": "#E7D6DF",
    "component-chip-border-neutral-hover": "#7A2E5D",
    "component-chip-border-neutral-selected": "#7A2E5D",
    "component-chip-content-neutral-default": "#121212",
    "component-chip-content-neutral-hover": "#121212",
    "component-chip-content-neutral-selected": "#7A2E5D",
    "component-input-border-color-primary-outlined-default": "#A08A96",
    "component-modal-background-primary-default": "#ffffff",
    "component-badge-background-primary": "#7A2E5D",
    "component-badge-content-primary": "#ffffff",
    "component-badge-radius-md": 8,
    "component-badge-radius-rounded": 64,
  },
};

export const fluxTheme: BrandTheme = {
  ...lifestyleTheme,
  name: "Hearst Flux",
  slug: "hearst-flux",
  fontHeadline: "Modern MT Pro",
  fontHeadlineWeight: 400,
  colors: {
    ...lifestyleTheme.colors,
    "1": "#292625",
    "2": "#EDEDED",
    "3": "#141211",
    "4": "#D6D6D6",
    "5": "#F7F7F7",
    "6": "#EFEFEF",
    "7": "#121212",
    "9": "#3B3735",
    "10": "#757575",
  },
  semanticColors: {
    ...lifestyleTheme.semanticColors,
    "palette-background-brand": "#292625",
    "palette-background-brand-active": "#141211",
    "palette-background-brand-hover": "#3B3735",
    "palette-background-default-link": "#292625",
    "palette-background-default-link-hover": "#3B3735",
    "palette-background-page": "#F7F7F7",
    "palette-background-subtle": "#EFEFEF",
    "palette-background-subtle-brand": "#EDEDED",
    "palette-background-utility": "#EDEDED",
    "palette-content-brand": "#292625",
    "palette-content-brand-active": "#141211",
    "palette-content-brand-hover": "#3B3735",
    "palette-content-default-link": "#292625",
    "palette-content-default-link-hover": "#3B3735",
  },
  componentTokens: {
    ...lifestyleTheme.componentTokens,
    "component-card-background-neutral": "#F7F7F7",
    "component-card-border-default": "#D6D6D6",
    "component-button-background-primary-solid-default": "#292625",
    "component-button-background-primary-solid-hover": "#3B3735",
    "component-button-background-primary-solid-active": "#141211",
    "component-button-background-primary-outlined-hover": "#EDEDED",
    "component-button-border-neutral-outlined-default": "#D6D6D6",
    "component-chip-background-neutral-hover": "#F7F7F7",
    "component-chip-background-neutral-selected": "#EDEDED",
    "component-chip-border-neutral-default": "#D6D6D6",
    "component-chip-border-neutral-hover": "#292625",
    "component-chip-border-neutral-selected": "#292625",
    "component-chip-content-neutral-selected": "#292625",
    "component-input-border-color-primary-outlined-default": "#757575",
    "component-badge-background-primary": "#292625",
  },
};

export const ewTheme: BrandTheme = {
  ...lifestyleTheme,
  name: "Hearst E&W",
  slug: "hearst-ew",
  fontHeadline: "Barlow Semi Condensed",
  fontHeadlineWeight: 800,
  fontHeadlineStretch: "normal",
  colors: {
    ...lifestyleTheme.colors,
    "1": "#C94B3B",
    "2": "#FFE0E4",
    "3": "#8F3329",
    "4": "#FFC2CB",
    "5": "#FFF5F6",
    "6": "#F7F7F7",
    "7": "#231F20",
    "9": "#AD3F32",
    "10": "#8A5A61",
  },
  semanticColors: {
    ...lifestyleTheme.semanticColors,
    "palette-background-brand": "#C94B3B",
    "palette-background-brand-active": "#8F3329",
    "palette-background-brand-hover": "#AD3F32",
    "palette-background-default-link": "#C94B3B",
    "palette-background-default-link-hover": "#8F3329",
    "palette-background-page": "#FFF5F6",
    "palette-background-subtle": "#F7F7F7",
    "palette-background-subtle-brand": "#FFE0E4",
    "palette-background-utility": "#FFE0E4",
    "palette-content-brand": "#C94B3B",
    "palette-content-brand-active": "#8F3329",
    "palette-content-brand-hover": "#AD3F32",
    "palette-content-default-link": "#C94B3B",
    "palette-content-default-link-hover": "#8F3329",
  },
  componentTokens: {
    ...lifestyleTheme.componentTokens,
    "component-card-background-neutral": "#FFF5F6",
    "component-card-border-default": "#E7D6DF",
    "component-button-background-primary-solid-default": "#C94B3B",
    "component-button-background-primary-solid-hover": "#AD3F32",
    "component-button-background-primary-solid-active": "#8F3329",
    "component-button-background-primary-outlined-hover": "#FFE0E4",
    "component-chip-background-neutral-hover": "#FFF5F6",
    "component-chip-background-neutral-selected": "#FFE0E4",
    "component-chip-border-neutral-hover": "#C94B3B",
    "component-chip-border-neutral-selected": "#C94B3B",
    "component-chip-content-neutral-selected": "#C94B3B",
    "component-input-border-color-primary-outlined-default": "#8A5A61",
    "component-badge-background-primary": "#C94B3B",
  },
};

export const hearstAllTheme: BrandTheme = {
  ...lifestyleTheme,
  name: "Hearst Magazines",
  slug: "hearst-all",
  fontSecondary: "Inter",
  fontHeadline: "Newsreader",
  fontHeadlineWeight: 700,
  colors: {
    ...lifestyleTheme.colors,
    "1": "#2B6FAF",
    "2": "#DCEBFA",
    "3": "#174C7D",
    "4": "#9FC5E8",
    "5": "#F4F8FC",
    "6": "#EDF4FB",
    "7": "#102A43",
    "9": "#1F65A6",
    "10": "#6A92B7",
  },
  semanticColors: {
    ...lifestyleTheme.semanticColors,
    "palette-background-brand": "#2B6FAF",
    "palette-background-brand-active": "#174C7D",
    "palette-background-brand-hover": "#1F65A6",
    "palette-background-default-link": "#2B6FAF",
    "palette-background-default-link-hover": "#174C7D",
    "palette-background-page": "#F4F8FC",
    "palette-background-subtle": "#EDF4FB",
    "palette-background-subtle-brand": "#DCEBFA",
    "palette-background-utility": "#DCEBFA",
    "palette-content-brand": "#2B6FAF",
    "palette-content-brand-active": "#174C7D",
    "palette-content-brand-hover": "#1F65A6",
    "palette-content-default-link": "#2B6FAF",
    "palette-content-default-link-hover": "#174C7D",
    "palette-content-subtle": "#5F6B7A",
  },
  componentTokens: {
    ...lifestyleTheme.componentTokens,
    "component-card-background-neutral": "#F4F8FC",
    "component-card-border-default": "#C7D9EA",
    "component-button-background-primary-solid-default": "#2B6FAF",
    "component-button-background-primary-solid-hover": "#1F65A6",
    "component-button-background-primary-solid-active": "#174C7D",
    "component-button-background-primary-outlined-hover": "#DCEBFA",
    "component-chip-background-neutral-hover": "#F4F8FC",
    "component-chip-background-neutral-selected": "#DCEBFA",
    "component-chip-border-neutral-hover": "#2B6FAF",
    "component-chip-border-neutral-selected": "#2B6FAF",
    "component-chip-content-neutral-selected": "#2B6FAF",
    "component-input-border-color-primary-outlined-default": "#6A92B7",
    "component-badge-background-primary": "#2B6FAF",
  },
};

export const localNewsTheme: BrandTheme = {
  ...hearstAllTheme,
  name: "Hearst Local News",
  slug: "hearst-local-news",
  colors: {
    ...hearstAllTheme.colors,
    "1": "#087A68",
    "2": "#DDF3E9",
    "3": "#055A4D",
    "4": "#A8DEC6",
    "5": "#F3FAF7",
    "6": "#EAF6F0",
    "7": "#153A2A",
    "9": "#066C5C",
    "10": "#5A9378",
  },
  semanticColors: {
    ...hearstAllTheme.semanticColors,
    "palette-background-brand": "#087A68",
    "palette-background-brand-active": "#055A4D",
    "palette-background-brand-hover": "#066C5C",
    "palette-background-default-link": "#087A68",
    "palette-background-default-link-hover": "#055A4D",
    "palette-background-page": "#F3FAF7",
    "palette-background-subtle": "#EAF6F0",
    "palette-background-subtle-brand": "#DDF3E9",
    "palette-background-utility": "#DDF3E9",
    "palette-content-brand": "#087A68",
    "palette-content-brand-active": "#055A4D",
    "palette-content-brand-hover": "#066C5C",
    "palette-content-default-link": "#087A68",
    "palette-content-default-link-hover": "#055A4D",
  },
  componentTokens: {
    ...hearstAllTheme.componentTokens,
    "component-card-background-neutral": "#F3FAF7",
    "component-card-border-default": "#B8DACB",
    "component-button-background-primary-solid-default": "#087A68",
    "component-button-background-primary-solid-hover": "#066C5C",
    "component-button-background-primary-solid-active": "#055A4D",
    "component-button-background-primary-outlined-hover": "#DDF3E9",
    "component-chip-background-neutral-hover": "#F3FAF7",
    "component-chip-background-neutral-selected": "#DDF3E9",
    "component-chip-border-neutral-hover": "#087A68",
    "component-chip-border-neutral-selected": "#087A68",
    "component-chip-content-neutral-selected": "#087A68",
    "component-input-border-color-primary-outlined-default": "#5A9378",
    "component-badge-background-primary": "#087A68",
  },
};

export const entertainmentTheme: BrandTheme = {
  ...hearstAllTheme,
  name: "A&E Family",
  slug: "hearst-entertainment",
  colors: {
    ...hearstAllTheme.colors,
    "1": "#B9913F",
    "2": "#F2DEAE",
    "3": "#80652C",
    "4": "#D5B869",
    "5": "#FBF8EF",
    "6": "#F5EBD2",
    "7": "#2A2215",
    "9": "#9E7B35",
    "10": "#8B7651",
  },
  semanticColors: {
    ...hearstAllTheme.semanticColors,
    "palette-background-brand": "#B9913F",
    "palette-background-brand-active": "#80652C",
    "palette-background-brand-hover": "#9E7B35",
    "palette-background-default-link": "#B9913F",
    "palette-background-default-link-hover": "#80652C",
    "palette-background-page": "#FBF8EF",
    "palette-background-subtle": "#F5EBD2",
    "palette-background-subtle-brand": "#F2DEAE",
    "palette-background-utility": "#F2DEAE",
    "palette-content-brand": "#B9913F",
    "palette-content-brand-active": "#80652C",
    "palette-content-brand-hover": "#9E7B35",
    "palette-content-default-link": "#B9913F",
    "palette-content-default-link-hover": "#80652C",
  },
  componentTokens: {
    ...hearstAllTheme.componentTokens,
    "component-card-background-neutral": "#FBF8EF",
    "component-card-border-default": "#DFCB9C",
    "component-button-background-primary-solid-default": "#B9913F",
    "component-button-background-primary-solid-hover": "#9E7B35",
    "component-button-background-primary-solid-active": "#80652C",
    "component-button-background-primary-outlined-hover": "#F2DEAE",
    "component-chip-background-neutral-hover": "#FBF8EF",
    "component-chip-background-neutral-selected": "#F2DEAE",
    "component-chip-border-neutral-hover": "#B9913F",
    "component-chip-border-neutral-selected": "#B9913F",
    "component-chip-content-neutral-selected": "#B9913F",
    "component-input-border-color-primary-outlined-default": "#8B7651",
    "component-badge-background-primary": "#B9913F",
  },
};

export const supplementalBrandProfiles: Record<
  string,
  {
    primary: string;
    secondary: string;
    fontDefault: string;
    fontHeadline: string;
    fontHeadlineWeight: number;
  }
> = {
  "bring-a-trailer": {
    primary: "#f40217",
    secondary: "#f5f5f5",
    fontDefault: "Open Sans",
    fontHeadline: "Open Sans",
    fontHeadlineWeight: 700,
  },
  "hot-rod": {
    primary: "#c11b17",
    secondary: "#141416",
    fontDefault: "Geist",
    fontHeadline: "Barlow Condensed",
    fontHeadlineWeight: 700,
  },
  motortrend: {
    primary: "#e90c17",
    secondary: "#141416",
    fontDefault: "Poppins",
    fontHeadline: "Poppins",
    fontHeadlineWeight: 700,
  },
};

export const themeOptions: BrandTheme[] = [hearstAllTheme, hearstPlusTheme, localNewsTheme, entertainmentTheme, lifestyleTheme, fluxTheme, ewTheme, ...brands];
