export const fluentEmojiAssetByIconName: Record<string, string> = {
  auction: "Receipt",
  "automotive-battery-02": "Battery",
  "bed-double": "Bed",
  bicycle: "Bicycle",
  "book-heart": "Books",
  "book-open-02": "Open book",
  "bookmark-check-02": "Bookmark tabs",
  "bubble-chat-spark": "Speech balloon",
  "building-06": "Office building",
  "calendar-03": "Calendar",
  "calendar-love-02": "Calendar",
  "camera-smile-02": "Camera",
  "camera-video": "Movie camera",
  "car-03": "Automobile",
  "car-signal": "Racing car",
  "chart-line-data-01": "Chart increasing",
  "check-list": "Clipboard",
  "checkmark-badge-02": "Check mark button",
  "cleaning-bucket": "Bucket",
  "clock-01": "Mantelpiece clock",
  "coffee-02": "Hot beverage",
  "cook-book": "Cooking",
  "court-house": "Classical building",
  crown: "Crown",
  "crown-02": "Crown",
  "dashboard-speed-01": "Stopwatch",
  "dress-03": "Dress",
  "dressing-table-01": "Mirror",
  "dressing-table-02": "Lipstick",
  "dumbbell-02": "Trophy",
  "dumbbell-03": "Trophy",
  energy: "High voltage",
  engine: "Gear",
  flower: "Tulip",
  "flower-pot": "Potted plant",
  gift: "Wrapped gift",
  "gift-card": "Wrapped gift",
  health: "Stethoscope",
  "heart-add": "Sparkling heart",
  "heart-check": "Red heart",
  "home-04": "House",
  "hot-price": "Money with wings",
  "house-03": "House",
  "house-heart": "House with garden",
  "in-love": "Smiling face with hearts",
  "kitchen-utensils": "Fork and knife",
  "leaf-02": "Herb",
  "leaf-03": "Leaf fluttering in wind",
  "mail-love-02": "Love letter",
  "mail-open": "Envelope",
  "map-pin": "Round pushpin",
  "maps-global-02": "World map",
  "maps-location-02": "World map",
  "medical-file": "Medical symbol",
  "mic-02": "Microphone",
  microchip: "Microbe",
  "money-03": "Dollar banknote",
  "money-bag-02": "Money bag",
  "money-saving-jar": "Money bag",
  "news-01": "Newspaper",
  "paint-board": "Artist palette",
  "paint-bucket": "Artist palette",
  "pen-tool-01": "Pen",
  "pencil-ruler": "Triangular ruler",
  "road-02": "Motorway",
  "road-location-02": "Motorway",
  "running-shoes": "Running shoe",
  salad: "Green salad",
  "seat-selector": "Seat",
  "shield-check": "Shield",
  "shopping-bag-check": "Shopping bags",
  "shopping-bag-favorite": "Shopping bags",
  "smart-phone-03": "Mobile phone",
  "smart-watch-03": "Watch",
  "sofa-01": "Couch and lamp",
  "sofa-02": "Couch and lamp",
  "sofa-03": "Couch and lamp",
  sparkles: "Sparkles",
  "spoon-and-fork": "Fork and knife with plate",
  "star-award-02": "Trophy",
  "star-face": "Star-struck",
  "stop-watch": "Stopwatch",
  "streering-wheel": "Wheel",
  "suit-02": "Necktie",
  "tent-tree": "Camping",
  "tool-case": "Toolbox",
  toolbox: "Toolbox",
  tools: "Hammer and wrench",
  "travel-bag": "Luggage",
  "tree-06": "Deciduous tree",
  "truck-delivery": "Delivery truck",
  "user-group-03": "Busts in silhouette",
  "user-star-02": "Bust in silhouette",
  "vintage-clock": "Mantelpiece clock",
  wellness: "Lotus",
  "workout-run": "Running shoe",
  "yoga-03": "Lotus",
};

export const fluentEmojiPng = (assetName: string) => {
  const fileName = `${assetName
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")}_3d.png`;

  return `https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/${encodeURIComponent(assetName)}/3D/${fileName}`;
};

export const fluentEmojiPngForIcon = (name: string) =>
  fluentEmojiPng(fluentEmojiAssetByIconName[name] ?? "Sparkles");
